### ISSUE TITLE
Error occurs with sql_mode=only_full_group_by

### ISSUE THREAD

**Issue by ismab** [in2code-de/luxletter#1]
Hello, 

Thank you for this new extension.

We need to use the backend module with "only_full_group_by" sql mode but this errors occurs :

(1/2) Doctrine\DBAL\Exception\DriverException
An exception occurred while executing 'select count(*) as count, properties, newsletter from tx_luxletter_domain_model_log where deleted=0 and status=300 group by properties order by count desc limit 8': Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'website.tx_luxletter_domain_model_log.newsletter' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

Do you have an idea on what we can do to use the extension without disabling only_full_group_by in MySql ?

**Comment by einpraegsam** [comment]
Hi,

I think I have to fix it, if this is a default setting in mysql. Is your setting default?
Can you please send me your complete sql mode line for testing here?

Alex

**Comment by einpraegsam** [comment]
I answer the question to myself:
https://dev.mysql.com/doc/refman/5.7/en/faqs-sql-modes.html#faq-mysql-what-default-mode

I should be per default:
`ONLY_FULL_GROUP_BY, STRICT_TRANS_TABLES, NO_ZERO_IN_DATE, NO_ZERO_DATE, ERROR_FOR_DIVISION_BY_ZERO, NO_AUTO_CREATE_USER, and NO_ENGINE_SUBSTITUTION`

So, long story short: I have to fix this error

**Comment by einpraegsam** [comment]
Fixed it in develop branch. Will be available in the upcoming release.
Thx for pointing me to this issue.
