### ISSUE TITLE
Failure on sending newsletter if fe_user data has no crdate

### ISSUE THREAD

**Issue by kanow** [in2code-de/luxletter#10]
I migrate tt_address data to fe_users and fe_groups for newsletter sending. Then I'm trying to send a newsletter. The scheduler task is failed, with following entry in sys_log:

`Core: Exception handler (CLI): Uncaught TYPO3 Exception: Call to a member function format() on null | Error thrown in file /app/web/typo3conf/ext/luxletter/Classes/Domain/Model/User.php in line 78`

After look into the code I have seen that crdate is used to generate a hash value. In my MySql query for the migration I didn't set the crdate. That was my problem.

It's easy for me to take the migration again and setting the crdate. But maybe it's a good tip in the readme/documentation for others they has to be migrate the tt_address data to fe_users.

**Comment by einpraegsam** [comment]
I added a note to FAQ and in addition I added a useful exception now for sys log. Will be released with the next version.
