### ISSUE TITLE
Error after 4.3.0 Update

### ISSUE THREAD

**Issue by ses2013** [in2code-de/luxletter#101]
Error: Origin 830 could not be converted into a valid url!
Reason: Given URL could not be parsed and accessed (Tried to read url: https://xxx.de/newsletter-16?type=1562349004). Typenum definition in site-configuration not set? Fluid Styled Mail Content TypoScript added? (1560709791)

I checked site-config and the TypoScript.
I disabled the "FormFields.html" changes
I debugged $newsletter

It worked with ver. 4.2.0 before.
Any further hints what has changed since ver. 4.2.0?
Cheers + Thanks

**Comment by einpraegsam** [comment]
I just tried but could not find a problem on my test instance. There is not that much change between 4.2 and 4.3 that could have such an impact in my eyes. Maybe a side-effect (cache, different configuration, etc...) occurs at the same time?
Can you please try to downgrade and test again?

**Comment by ses2013** [comment]
It seems there was a curl problem with the ssl certificate since 30.09.
So sorry for the confusion but it might be helpfull for other´s to know about such a case …

**Comment by einpraegsam** [comment]
Thx for your final feedback. I just updated the FAQ section in the documentation if anyone else have the same issue.
