### ISSUE TITLE
Users without email block the sending queue

### ISSUE THREAD

**Issue by ismab** [in2code-de/luxletter#11]
Hello,
We have noticed that the emails sending queue is blocked when a user doesnt have an email (this causes an error in the scheduled task).
We have to send newsletters to a large number of people and sometime users with no email end up in the newsletter group.
Would it be possible in a future version of the extension to no longer take into account users with empty emails (as for deleted or disabled users) in order to finish the sending for the users remaining in the queue ?
Thank you for your work on this extension.

**Comment by einpraegsam** [comment]
Fixed in version 1.2.2 - thx for reporting
