### ISSUE TITLE
TYPO3 Extension Award - Best Documentation 2021

### ISSUE THREAD

**Issue by sypets** [in2code-de/luxletter#110]
This issue is for your information only. Please feel free to close

---

**Congratulations**! :sparkles: :tada: 
Your extension has been nominated for the **TYPO3 Extension Award - Best Documentation 2021**.

Three extensions will be chosen as winners by a community vote. In case your extension wins, you will be notified shortly after the voting.

> Voting: November 24 - December 8, 2021 (2 weeks)

In order to vote for an extension:

1. Go to https://extensions.typo3.org and login
2. Click on the “Vote now” button on https://extensions.typo3.org/extension-documentation-award
3. Give 3 points, 2 points and 1 point each for each extension, by clicking on the radio button

Please also look for news on https://typo3.org in the next few days or look on “[Community news](https://typo3.org/project/news/community-1)” for a more detailed description.

Thank you for making your extension available for the TYPO3 community.

Best of luck - and keep inspiring people to share. 

Sybille :smiley:

If you have any questions, please contact me on TYPO3 Slack (`@Sy`).

**Comment by einpraegsam** [comment]
Thank you for the information @sypets - any hints who nominated some extensions yesterday?
Note: I'm not sure if this extension is allowed because there is no documentation on docs.typo3.org (you know the markdown thing) :)

**Comment by sypets** [comment]
> any hints who nominated some extensions yesterday?
I have no access to this information. I just have the list of nominated extensions.

> Note: I'm not sure if this extension is allowed because there is no documentation on docs.typo3.org (you know the markdown thing) :)

Having docs on docs.typo3.org was not a requisite - it is enough to have documentation. Though I would like to see more extensions render their docs on docs.typo3.org  - that was not the intention. Having documentation at all was the criteria (besides the other criteria like Composer and v11 support). 

So, your documentation is "in", do not worry about it and there are others who are not rendered on docs.typo3.org.

(Myself, I am ambiguous about the "Markdown" thing - I do not want to pressure anyone to use .rst. But it is the (better) supported format for docs.typo3.org and rendering it there gives the extensions more visibilty. But that is for everyone to decide themselves.)

**Comment by einpraegsam** [comment]
Thanks for the explanation and your time. I will close this "issue" :)
