### ISSUE TITLE
Scheduler: Ausführung fehlgeschlagen: 1521716628, No site found for identifier newsletter

### ISSUE THREAD

**Issue by stephangrass** [in2code-de/luxletter#117]
Hi.

I have a multisite installation. One site is dedicated to the newsletter.
I get the following error in the scheduler:

Ausführung fehlgeschlagen: 1521716628, No site found for identifier newsletter

Do I have to configure anything else?

Thanks
Stephan

**Comment by einpraegsam** [comment]
Hard to say. Some points:
- Did you add the unsubscribe page identifier to every site configuration (pid can be outside the site but must be valid)
- Are you using the very latest version of luxletter?
- What about the preview in the backend? Did this work?
- What about sending the newsletter from CLI by hand? Are there more information about the problem?

**Comment by stephangrass** [comment]
> Did you add the unsubscribe page identifier to every site configuration (pid can be outside the site but must be valid)
Yes

> Are you using the very latest version of luxletter?
V 11.1.0

> What about the preview in the backend? Did this work?
Yes, the preview works

> What about sending the newsletter from CLI by hand?
Sending by hand will work

> Are there more information about the problem?
not really

**Comment by einpraegsam** [comment]
Strange, when sending over CLI works but not with scheduler. 

Now we're coming to the playtime: 
- Maybe different rights between the cronjob and your SSH-User? You could test to call `./vendor/bin/typo3cms luxletter:queue` directly in crontab settings
- Debugging

**Comment by stephangrass** [comment]
Sorry, I haven't sent the newsletter via CLI yet.
I can send the newsletter manually from the scheduler. So if I trigger the task manually.

Sending by `./vendor/bin/typo3cms luxletter:queue` will work.

**Comment by einpraegsam** [comment]
Sorry, running out of ideas. Probably a problem with rights on the server. Last option: Debugging and see what's wrong here.

**Comment by stephangrass** [comment]
ok, thanks for the first one. I will start debugging ...

**Comment by einpraegsam** [comment]
Any final feedback?
