### ISSUE TITLE
undeliverable newsletter emails to FE users

### ISSUE THREAD

**Issue by webworker-united** [in2code-de/luxletter#118]
Hi,

I have a question regarding undeliverable newsletter emails to FE users who may no longer exist. 

Is there any way to filter out these users and automatically disable or even delete them so they are not included in the next newsletter mailing?

Thanks for your input

**Comment by einpraegsam** [comment]
There is no bounce management yet - duplicate to https://github.com/in2code-de/luxletter/issues/53
