### ISSUE TITLE
Strange error after installation

### ISSUE THREAD

**Issue by koehlersimon** [in2code-de/luxletter#12]
Hey thank you for the new version of luxletter! I have just downloaded and installed it into a 9.5.8 TYPO3 on a local machine. When I click on "Reciever" in the backend module I get the following error. Do you have any idea why it appears? It's a fresh installation with no other extensions.

```
Oops, an error occurred!
Folder "/t39/typo3conf/ext/luxletter/Resources/Public/Images/Lux/ReceiverList.png/" does not exist. 
```

**Comment by einpraegsam** [comment]
Beside that Folder should be File - would be the path correct? Is the file accessable on your system via Apache?
Can you please try to delete lines:
Resources/Private/Templates/Newsletter/Receiver.html:19
Resources/Private/Templates/Newsletter/Receiver.html:34

And give me feedback?

**Comment by koehlersimon** [comment]
Thanks for your fast reply. Yes it works without the images. I have changed the two lines to:
```
<f:image src="EXT:luxletter/Resources/Public/Images/Lux/ReceiverList.png" width="800c" height="400c" style="max-width: 100%;" />
<f:image src="EXT:luxletter/Resources/Public/Images/Lux/ReceiverDetail.png" width="800c" height="400c" style="max-width: 100%;" />
```
That's okay for now ;-)

**Comment by einpraegsam** [comment]
That's strange. Also the other code should work. 
I will close this issue for now. But if other have the same issue, I will change the lines as you wrote.
