### ISSUE TITLE
Wrong check in Services.php

### ISSUE THREAD

**Issue by georgringer** [in2code-de/luxletter#120]
see discussion in https://forge.typo3.org/issues/97665

**Comment by einpraegsam** [comment]
Thx for reporting. Release 13.0.1 is on it's way

**Comment by georgringer** [comment]
thanks a lot! 👍

**Comment by einpraegsam** [comment]
Thx to the hint of Christian, I did a copy and paste mistake that should be fixed in 13.0.2 now.
https://github.com/in2code-de/luxletter/commit/d069abc981515830c3a95370374d5b44cf775f52#commitcomment-74309453
