### ISSUE TITLE
the preview looks good but the mail does not

### ISSUE THREAD

**Issue by typo3rel** [in2code-de/luxletter#13]
Hi,

to customize /Mail/NewsletterContainer.html
these settings only work for the preview?

```
plugin.tx_luxletter_fe {
  view {
    templateRootPaths {
      10 = fileadmin/tmpl/Templates/Luxletter/
    }
  }      
}
```

only if I also overwrite the module template will the mail be rendered correctly?

```
plugin.tx_luxletter_fe {
  view {
    templateRootPaths {
      10 = fileadmin/tmpl/Templates/Luxletter/
    }
  }      
}
# Copy plugin configuration to module configuration to just use one configuration for both places.
module.tx_luxletter < plugin.tx_luxletter_fe
```

**Comment by einpraegsam** [comment]
Yes, but if you copy it to module everything works as expected?

**Comment by typo3rel** [comment]
Yes it works but according to the docu, that was not clear to us

**Comment by peerlight** [comment]
Does not work for me. 

plugin.tx_luxletter_fe and module.tx_luxletter have same settings, checked in Backend in TSObjectBrowser

Preview shows correct own template but mail uses standard from luxletter/Resources/Private/Templates/Mail/NewsletterContainer.html

any hints to debug this?

**Comment by einpraegsam** [comment]
Look at the updated documentation: https://github.com/in2code-de/luxletter/blob/develop/Documentation/Newsletter/Index.md#zurb-foundation-and-newsletter-wrapping
You also have to define your templates for module.

**Comment by peerlight** [comment]
Thanks for the hint. 

But templates for module were set - on the folder in which the newsletter pages are edited. That was the problem.

Preview / rendered newsletters are saved in DB with page uid of site root page not newsletter page (or parent folder like in direct_mail) . So defining templates for module on site root solved the issue.

This could be added to the docs.

**Comment by einpraegsam** [comment]
Thx, fixed
