### ISSUE TITLE
Subscribe Newsletter Form

### ISSUE THREAD

**Issue by PittRo** [in2code-de/luxletter#135]
hello, 

first oof all, thanks for creating the only one extension which is still working with typo3 11LTS. Like everyone who is going to use this extension, we need a subscription form. Where is the feature and how did you arrange that yet? Fe_users always need a password for registration but in case of a nl subscription there is one password too much of a good thing. We are working on "sf_register" at the moment but is there any easier way to handle this?

**Comment by einpraegsam** [comment]
Thx for your feedback.
Anyways, the extension is based on newsletter generation and sending. But a registration in frontend is not part of it.
On one hand fe_user record can also be imported over an interface or managed by editors by hand and on the other hand, this is - as on my technical view - a complete different task.
So, there are no plans for a registration, especially there are extensions like femanager or as you mentionend sf_register for such a task if needed.

**Comment by PittRo** [comment]
ok thanks for reply
