### ISSUE TITLE
Unclear error message for delayed ajax load

### ISSUE THREAD

**Issue by f7media** [in2code-de/luxletter#136]
When creating a new newsletter ("Add new newsletter"), the error message 
> Newsletter is not ready yet - Please fill all mandatory fields

appears irregularly in step 3 - although all fields have been filled in.

According to our developers, this is caused by the fact that after selecting the list of recipients ("Receiver§) and the source ("Where is the newsletter located?"), Luxletter loads recipients and the preview via ajax. But the system does not wait for the ajax load to be completed and, in the case of slow servers or large ajax data, gives the error message mentioned above. However, this is not clear to the editor, as all fields are filled in correctly.

It would be nice if the system would wait in this case for the ajax load to complete before allowing the user to go to the next step.

**Comment by einpraegsam** [comment]
We also faced this issue and I think we have fixed it in https://github.com/in2code-de/luxletter/commit/43fac09cf558524ed43c4ed5173cd922499e4d55 but only for multilanguage mode.
Does luxletter run in old or in multilanguage mode on your server?

**Comment by f7media** [comment]
We just updated to 14.1 and can confirm that the bug is fixed.
