### ISSUE TITLE
Hidden dependency to EXT:lux -> error

### ISSUE THREAD

**Issue by lochmueller** [in2code-de/luxletter#138]
Hey Alex,

I have an installation with EXT:luxletter in the current version and without EXT:lux. The Newsletter system is broken, because there are a hidden dependency, because classes from EXT:lux are loaded. This result in this error "Class In2code\Lux\Domain\Model\Category does not exist. Reflection failed.", because this line load the class https://github.com/in2code-de/luxletter/blob/develop/Classes/Domain/Model/Dto/Filter.php#L33

If you search for "\Lux\" there are more classes loaded/needed.

Is EXT:lux is a requirement? I think the namespace is wrong, because in this case there is also a Category obeject in EXT:luxletter.

Regards,
Tim

**Comment by einpraegsam** [comment]
No, it's not needed to also install EXT:lux - I will provide a quick solution

**Comment by einpraegsam** [comment]
Hi @lochmueller, I just pushed a fix to develop branch. This should fix the issue. Can you confirm this?

Sorry, for the inconveniences

**Comment by lochmueller** [comment]
Hey @einpraegsam 
Looks great in the first view. Thanks for the quick fix.
Regards,
Tim

**Comment by einpraegsam** [comment]
Thx, I just released 17.0.1 with a bugfix

**Comment by ses2013** [comment]
There seems to be more ext:lux errors

(1/2) TYPO3Fluid\Fluid\Core\Parser\UnknownNamespaceException
Fluid parse error in template partial_Miscellaneous/Pagination_4b472cee1c719acc7e76caffab8c75098a9ec20c, line 10 at character 118. Error: Unknown Namespace: lux (error code 0).

Template source chunk:
<li class="previous"> <a href="{lux:pagination.uri(arguments:'{currentPage:pagination.previousPageNumber}',name:name)}" title="previous" class="page-link"> &lt; </a> </li>

**Comment by einpraegsam** [comment]
Thx, same copy and paste problem with a different source. I just published 17.0.2.
