### ISSUE TITLE
Email gets send multiple time [twice] to the same recipient

### ISSUE THREAD

**Issue by ses2013** [in2code-de/luxletter#145]
Hi there,
I get reports from members of the mailinglist that they get the newsletter email twice to the same/ident emailadress.
Could there be something inbetween:
Smtp, Scheduler, Cron, luxletter to cause this behaviour?
I have no idea where to look for the error.
Thx for any input.
Cheers

**Comment by einpraegsam** [comment]
Can you check the entries of the table `tx_luxletter_domain_model_queue`. Are there 2 entries to the same email address with the same newsletter uid?

**Comment by ses2013** [comment]
No there is only one!

**Comment by einpraegsam** [comment]
So it sounds to me that this is not an issue of LUXletter. Maybe a problem with the mailserver? I would ask the server admin to look into the logs what's happened there.

**Comment by einpraegsam** [comment]
Any final feedback?

**Comment by ses2013** [comment]
As noone else report anythink like this it must be the server enviroment … so feel free to close it.

**Comment by einpraegsam** [comment]
Thx
