### ISSUE TITLE
Error Class 'TijsVerkoyen\CssToInlineStyles\CssToInlineStyles' not found

### ISSUE THREAD

**Issue by ninar92** [in2code-de/luxletter#146]
Hello,

i installed the extension without composer and get this Error in the preview of the newsletter 
![image](https://user-images.githubusercontent.com/96298197/197754299-53e1cf86-ff89-44b4-9c41-2e25f60ae882.png)

What can i do? Can anyone help please?

Its a Typo3 11.5.16 installation..

**Comment by ninar92** [comment]
Okay but I can install the extension in composer mode even if my Typo3 installation was not installed with composer and also all other extensions were not installed with composer? And if yes, how can i do it? And if not, does that mean I can't use the extension?

**Comment by einpraegsam** [comment]
No, the extension can only be installed via composer. This means, that also TYPO3 must be installed via composer. Both means, that TYPO3 and every extension is running in the composer mode.

**Comment by ninar92** [comment]
Ok thank you very much for your quick answer, but that's really too bad. Then i cant use the extension...
