### ISSUE TITLE
Origin could not be converted into a valid url!

### ISSUE THREAD

**Issue by estudio-kintek** [in2code-de/luxletter#147]
We've tried to create a new Newsletter in a Typo3 version 9.5.22.

After 2 first steps of the process, at the last one with the preview of the newsletter, we've got an error message:

"Origin #page_id could not be converted into a valid url!
Message: Given URL could not be parsed and accessed (Tried to read url: https://domain/segment/page?type=1562349004). Typenum definition in site-configuration not set? Fluid Styled Mail Content TypoScript added?"

We've followed the configuration steps ([https://github.com/in2code-de/luxletter/blob/develop/Documentation/Installation/Index.md](https://github.com/in2code-de/luxletter/blob/develop/Documentation/Installation/Index.md)):

- We have checked that main configuration values like the typenum are set.
- We have included the TypoScripts in the root template.
- We have defined fe_groups for the Newsletter.
- We have add a page with a luxletter teaser element as unique main content, the one we try to set creating the newsletter.

When we check the "var_dump" of different variables in the code of the process, we can see that variable $body is NULL in the request headers.

Anyone knows what's reason of the error?

Thank you!

**Comment by estudio-kintek** [comment]
We've tried and we have no problems in both cases.

We have also tried to install a clear typo3 9.5.31 installation with the luxletter extension and also have the same problem.

Thank you!

**Comment by einpraegsam** [comment]
This is a bit strange so far and I'm running out of ideas without deeper debugging...

**Comment by estudio-kintek** [comment]
Finnally it worked! The reason was just silly...

At luxletter configuration, we haven't set an unsuscribe PID of a page with the unsuscribe plugin element of luxletter. We have set a page with other kind of form, but it seems that luxletter requires that specific element to work correctly.

We have try to set the unsuscribe plugin of luxletter at the page with the PID set in luxletter configuration and now it works.

Thank you anyway for your attention!

**Comment by einpraegsam** [comment]
Ah ok. That's why we improved the error message back for version 11.0.0 in march this year (commit https://github.com/in2code-de/luxletter/commit/2079c390b5d459c44fd173c2bcc466e906b84d2f). That's another reason to update your TYPO3 to 10 or 11.
Thx for your final feedback.
