### ISSUE TITLE
ext_typoscript_setup.txt overwrites sitepackage settings

### ISSUE THREAD

**Issue by Make66** [in2code-de/luxletter#148]
Templates are included in the following sequence:
1: "Basic Typoscript (luxletter)" in the root template
2. sitepackage extension customizes settings i.e. template paths after 1:
3. ext_typoscript_setup.txt in the root of the extension, restores basic settings

As proven by template analyzer, 
My solution: delete ext_typoscript_setup.txt (is anyhow old fashioned)

**Comment by einpraegsam** [comment]
Did you see the notes on https://github.com/in2code-de/luxletter/blob/develop/Documentation/Tech/Index.md#change-templates (the notes below the example)?
At the moment we still work with ext_typoscript_setup.txt.

**Comment by Make66** [comment]
Damn - RTFM! And I thought I found one...
;-)
Good workaround!

**Comment by einpraegsam** [comment]
Thx for the final feedback
