### ISSUE TITLE
Newsletter preview in backend is not correct, page type is missing

### ISSUE THREAD

**Issue by kanow** [in2code-de/luxletter#15]
Page type setting in extension configuration is set but will be not respected. If a url with the type is inserted (e.g. https//www.mysite.de/newsletterpage/?type=25) then it works. Only with the page id not.

See here: https://forge.typo3.org/issues/87817

The pageTypeDecorator in TYPO3 Core is removing all types that can't be mapped.Those patch will be help till the new release of TYPO3 fix that issue.

https://review.typo3.org/c/Packages/TYPO3.CMS/+/62811

**Comment by einpraegsam** [comment]
I could not reproduce this issue in the latest version - is this still a thing?

**Comment by kanow** [comment]
I tested this with TYPO3 9.5.14. Issue is solved. Preview is working fine.
