### ISSUE TITLE
missing typenum 1560777975	Needed for a prerendering

### ISSUE THREAD

**Issue by PittRo** [in2code-de/luxletter#153]
This my error online, at my local ddev testsystem everything is working.
My you help us out again?
Error: Origin 112 could not be converted into a valid url!
Reason: Given URL could not be parsed and accessed (Tried to read url: ...../newsletter-12-2022/newsletter.html). Typenum definition in site-configuration not set? Fluid Styled Mail Content TypoScript added? (1560709791)

in our site configuration is following set:
....
  PageTypeSuffix:
    type: PageType
    default: /
    index: ''
    suffix: /
    map:
      preview.html: 1560777975
      newsletter.html: 1562349004
      pixel.png: 1561894816
...
but without setting the routes it does not work propertly.

In case of typing https:......./newsletter-12-2022/preview.html with the route settings an further error occurs
Oops, an error occurred! Code: 20221212170848bb78441c

Another error appears, if we post an preview via email and button but it works local 
(ajax post https://...../typo3/ajax/luxletter/testMail?token=078e300c3a00faf573cfa8ca6b9a6c4c79852303&origin=112&email=......&subject=&configuration=1&layout=B2BNlContainer)
503
Oops, an error occurred!
Could not read template file with given path and filename
More information regarding this error might be available 

running System is Typo3 11.5.19

**Comment by einpraegsam** [comment]
Did you check the FAQ related to this question? https://github.com/in2code-de/luxletter/blob/develop/Documentation/Tech/Index.md#mail-could-not-be-parsed-in-preview-when-adding-an-origin

**Comment by PittRo** [comment]
Dear einpraegsam,
yes how i wrote above, i added this site configuration, to my custom 3 mappings
....
PageTypeSuffix:
type: PageType
default: /
index: ''
suffix: /
map:
preview.html: 1560777975
newsletter.html: 1562349004
pixel.png: 1561894816
...

**Comment by einpraegsam** [comment]
What if you debug `$exception` in https://github.com/in2code-de/luxletter/blob/develop/Classes/Domain/Service/Parsing/NewsletterUrl.php#L272

**Comment by PittRo** [comment]
debug output via e-mail

**Comment by einpraegsam** [comment]
Thx for the mail. The main point seems to be:
```
cURL error 28: Connection timed out after 10001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://domain.de/newsletter-12-2022/newsletter.html
```
So CURL seems not be allowed to read the target. CURL on CLI works for you?

**Comment by PittRo** [comment]
Thanks, i guess the security settings block it.
