### ISSUE TITLE
Given filename XXX is invalid

### ISSUE THREAD

**Issue by ses2013** [in2code-de/luxletter#154]
After updateting to 18.0.0 without chaning anythink I get the Newsletter Preview Error

```
"Error: Origin 830 could not be converted into a valid url!
Reason: Given filename (XXX) is invalid (1635492796)"
```
The file exists. Is named correctly and worked before.
Any suggestions? Thanks.

**Comment by einpraegsam** [comment]
Did you change your TypoScript like it's described here: https://github.com/in2code-de/luxletter/blob/develop/Documentation/Changelog/Index.md#upgrade-to-18x

**Comment by ses2013** [comment]
Oh man I am so sorry.
I always look up the changelog.
Solved.

**Comment by einpraegsam** [comment]
Thx for the final feedback
