### ISSUE TITLE
503 Could not read template file with given path and filename

### ISSUE THREAD

**Issue by PittRo** [in2code-de/luxletter#156]
Dear,

how i already mentioned here https://github.com/in2code-de/luxletter/issues/153
the preview newsletter post does not work. Where can i debug this?
The request URL is https://DOMAIN.DE/typo3/ajax/luxletter/testMail?token=ae702b44bc630907335d903b17c2b8143884fb5d&origin=112&email=mail@mail.com&subject=&configuration=1&layout=B2BNlContainer

The ajax request https://DOMAIN/typo3/ajax/system-information/render?token=d5d478592d62317b7e691a0ef30bfd9ab35d00db&skipSessionUpdate=1 works fine

Typo3 11. 5.19

**Comment by einpraegsam** [comment]
Did you see my last comment in #153 ?

**Comment by PittRo** [comment]
Dear einpraegsam,
Curl is not responsible we checked this out. I debuged already the request I mentioned above hangs up while  
[Line 80 in TestMail.php
$parseUrlService = GeneralUtility::makeInstance(NewsletterUrl::class, $origin, $layout, $language)
                ->setModeTestmail();](https://github.com/in2code-de/luxletter/blob/develop/Classes/Mail/TestMail.php#L80)

NewsletterUrl::class === In2code\Luxletter\Domain\Service\Parsing\NewsletterUrl at that point

furthermore i debuged at https://github.com/in2code-de/luxletter/blob/develop/Classes/Domain/Service/LayoutService.php#L79
$this->getLayoutPath() . $layout . '.html' is at that point wrong the output is EXT:luxletter/Resources/Private/Templates/Mail/B2BNlContainer.html
and not
EXT:sitepackage/Resources/Private/Templates/Mail/B2BNlContainer.html
how we configured in sitepackage > setup.typoscript and in root-template again, cause it do not work at only one place.
By the way we folowed the right oder of https://github.com/in2code-de/luxletter/blob/develop/Documentation/Installation/Index.md#typoscript and place even our sitepackage below

**Comment by julianhofmann** [comment]
In general, this works, i.e. the issue could be closed.

To find a solution for you, it might be good if you show your configuration (or relevant sections). Because the cause of your problem seems to lie there.

**Comment by einpraegsam** [comment]
Thx for the Feedback
