### ISSUE TITLE
Scheduler task fails with malformed url

### ISSUE THREAD

**Issue by magicHatOfTYPO3** [in2code-de/luxletter#159]
Sending emails with the scheduler task throws errors in the logs 

The parsedUri \"http:///srv/www/htdocs/website/vendor/bin/typo3\" appears to be malformed

(which is obviously true). I have no clue, why luxletter tries to use the path to the typo3 bin as URL, which cannot work. 
The system is behind a reverse proxy (maybe correlated).

I try to reproduce the error in my local machine, yet without success. 

```
Tue, 13 Dec 2022 14:21:01 +0100 [ERROR] request="03f27bd83c85f" component="TYPO3.CMS.Scheduler.Task.AbstractTask": Task failed to execute successfully. Class: TYPO3\CMS\Scheduler\Task\AbstractTask, UID: 5- InvalidArgumentException: The parsedUri "http:///srv/www/htdocs/website/vendor/bin/typo3" appears to be malformed, in file /srv/www/htdocs/website/vendor/typo3/cms-core/Classes/Http/Uri.php:125 - {"class":"TYPO3\\CMS\\Scheduler\\Task\\AbstractTask","uid":5,"exception":"InvalidArgumentException: The parsedUri \"http:///srv/www/htdocs/website/vendor/bin/typo3\" appears to be malformed in /srv/www/htdocs/website/vendor/typo3/cms-core/Classes/Http/Uri.php:125\nStack trace:\n
#0 /srv/www/htdocs/website/vendor/typo3/cms-core/Classes/Http/Uri.php(111): TYPO3\\CMS\\Core\\Http\\Uri->parseUri()\n
#1 /srv/www/htdocs/website/vendor/typo3/cms-core/Classes/Http/ServerRequestFactory.php(65): TYPO3\\CMS\\Core\\Http\\Uri->__construct()\n
```

**Comment by einpraegsam** [comment]
Hi,

is there a backtrace where we can figure out, which class triggers Uri.php?

Alex

**Comment by einpraegsam** [comment]
Any feedback?

**Comment by magicHatOfTYPO3** [comment]
Hi Alex, 

I'm not 100% sure, but it might be related to the customers server itself. Currently we have configured the Luxletter Mailserver configuration explicitly (and do not use the TYPO3 mailserver configuration, although it's identical) and it seems to work then. There are running some tests at the moment, but maybe this have solved the problem.
