### ISSUE TITLE
Title or luxletter_subject in the email?

### ISSUE THREAD

**Issue by fixpunkt-systeme** [in2code-de/luxletter#160]
Is it possible to use page-data like title or luxletter_subject in the email-template NewsletterContainer.html?
I guess only this variables are available: 
content, user, site, settings
therefore I think it is not possible.
But it would be great.

**Comment by einpraegsam** [comment]
Not yet, PR is welcome. 
Duplicated to https://github.com/in2code-de/luxletter/issues/152
