### ISSUE TITLE
Error Installation

### ISSUE THREAD

**Issue by Mary-SB** [in2code-de/luxletter#162]
Class "TijsVerkoyen\CssToInlineStyles\CssToInlineStyles" not found

**Comment by einpraegsam** [comment]
The extension need the composer mode (see documentation).

**Comment by Mary-SB** [comment]
Thank you for the prompt reply!
Is there a version of luxletter in traditional mode that runs with Typo3 11?

**Comment by einpraegsam** [comment]
No, there is no other version
