### ISSUE TITLE
Newsletter not selectable in dropdown menu

### ISSUE THREAD

**Issue by danaron** [in2code-de/luxletter#167]
I do have two sites using the luxletter. Both are on the same stage: Typo3 11.5.22 Luxletter 19.
In one installation i can easely choose the newsletter to be parsed by filling in it or URL, the other installation has a empty dropdown where nothing can be choosen. See esmaple pics. What can I do?
Thanks for your help.
![screencapture-duovet-ch-typo3-module-lux-LuxletterLuxletter-2023-01-30-09_26_30](https://user-images.githubusercontent.com/9381733/215425926-b519eeff-975f-4892-bf4f-c95f3dacde1c.png)
![screencapture-aloco-ch-typo3-module-lux-LuxletterLuxletter-2023-01-30-09_27_08](https://user-images.githubusercontent.com/9381733/215426075-0483e361-9c27-4adc-83c9-0292d73ad494.png)

**Comment by einpraegsam** [comment]
Hi, this depends on your settings. See "multilanguage mode" in basic extensions settings.
With activated mlm you have to add pages of type "newsletter" anywhere in your pagetree. After that, you can choose one of them in the select field.
