### ISSUE TITLE
Use FE_User without username and password

### ISSUE THREAD

**Issue by jokuwebco** [in2code-de/luxletter#173]
Hello all,

how to create fe_user without "password" and "username"? Because these are a mandatory field in TYPO3 11, but I also do not want to disable them for the complete site. 
Furthermore I would be interested in how fe_user with email addresses can be read in automatically, for example via a CSV file? 

Thank you in advance for your support.

**Comment by einpraegsam** [comment]
Please don't use github issues for support questions, to keep the issue list as short as possible. Slack or Stackoverflow would be the better place.
