### ISSUE TITLE
Wrong sendout-statistics

### ISSUE THREAD

**Issue by julianhofmann** [in2code-de/luxletter#180]
New newsletters are showing a "50% sent"-state immediately after saving them...

Maybe regression of #177 ?

![Bildschirmfoto 2023-07-07 um 08 59 42](https://github.com/in2code-de/luxletter/assets/25646388/1bf4bd4d-5047-4492-88c9-abc9773f3ffb)

**Comment by julianhofmann** [comment]
Not quite sure, why this happens. Both newsletters above have been sent to some receivers via "Newsletter testweise versenden" - but these mails should not be counted... For a newsletter with completely new receivers, the counting seems correct.

**Comment by einpraegsam** [comment]
Maybe this is a regression of the 22.0.0 release. Does the error occurs in version 21?

**Comment by julianhofmann** [comment]
I noticed it in v17.6, but #177 was only backported and therefore v22 should behave similarly.

Hints, reports and feedback about the behavior are welcome.

**Comment by julianhofmann** [comment]
Is a regression of #177 :-/
Just switched back to 17.5.1 - and the same two newsletters are showing correct data after they are created. Switching forward to 17.6.1, and states are wrong again.

**Comment by rialDave** [comment]
I can confirm this issue with exactly 50% progress when all emails are sent out (even with over 19k queue entries it's exactly 50%).

**Comment by einpraegsam** [comment]
I just released new versions with a bugfix - thx to @julianhofmann
