### ISSUE TITLE
Test email: Success-message should be distinguishable 

### ISSUE THREAD

**Issue by julianhofmann** [in2code-de/luxletter#181]
When testing a newsletter (especially while setting up the template), you'll send the test mail several times to the same receiver. When resubmitting the form you get no visible feedback if something happened - the screen looks like before (except for the quick flash when reloading).

![screenshot-2023 07 07-09_31_56](https://github.com/in2code-de/luxletter/assets/25646388/f54ea421-0c9b-44bf-923a-b843312880e7)

Adding the receiver and the time to the success-message would be helpful

![Bildschirmfoto 2023-07-07 um 09 36 06](https://github.com/in2code-de/luxletter/assets/25646388/2cc49d20-0984-4048-8bae-dd11f6418ffb)

**Comment by einpraegsam** [comment]
Good idea, PR are welcome :)

**Comment by einpraegsam** [comment]
Thx, I just pushed a new feature for this issue. We now simply add the number of already sent testmails (1 for the first mail, 2 for the second, and so on)
