### ISSUE TITLE
error in step3 preview: Class "TijsVerkoyen\CssToInlineStyles\CssToInlineStyles" not found

### ISSUE THREAD

**Issue by HorstBaumann** [in2code-de/luxletter#183]
TYPO3: 11.5.29 (classic installation - no composer!)
luxletter: 21.0.0

everything works fine, until step3, where i get the error:
**503
Oops, an error occurred!
Class "TijsVerkoyen\CssToInlineStyles\CssToInlineStyles" not found**

also the cronjob did not work and shows the same message

How can i implement the package from https://github.com/tijsverkoyen/CssToInlineStyles
or is there a way to deactivate the CssToInlineStyles-process ?

thanks

**Comment by einpraegsam** [comment]
This sounds to me that you didn't install LUXletter via composer as it is requested in the documentation?

**Comment by HorstBaumann** [comment]
yes, i don't have shell access to our clients server and therefore none composer

**Comment by einpraegsam** [comment]
Thx for the final feedback. This is not a failure but more an installation issue.
