### ISSUE TITLE
v17: Correction of backport deviation

### ISSUE THREAD

**Issue by julianhofmann** [in2code-de/luxletter#189]
While backporting #178 for v17 in https://github.com/in2code-de/luxletter/commit/fe54de2fa47adf06548069abd0f60b41e0d2e275, changes of `QueueRepository::findAllByNewsletterAndDispatchedStatus(` have gotten lost.

(Thanks to Dave, who discovered this!)

**Comment by einpraegsam** [comment]
This is already in branch 17 and available via 17.6.3 - can we close this issue?
