### ISSUE TITLE
Parsed content is inserted into variable {content} in FLUID comment and saved in DB

### ISSUE THREAD

**Issue by peerlight** [in2code-de/luxletter#19]
When doing step 2 in BE the parsed content is inserted into variable {content} in FLUID comment of NewsletterContianer.html and saved into DB.

This should not be necessary. Or am I wrong?

Found this while investigating #13

**Comment by einpraegsam** [comment]
PR are welcome :)

**Comment by peerlight** [comment]
just escape {content}  or rename in <f:comment>

Am 16.03.20 um 17:14 schrieb Alex Kellner:
> PR are welcome :)
>
