### ISSUE TITLE
Validation error when clicking through tabs when creating a newsletter

### ISSUE THREAD

**Issue by rialDave** [in2code-de/luxletter#193]
When I'm clicking through the "step"-tabs when creating a new newsletter in the luxletter module, after selecting everything that's needed, there is a message stating that some required fields aren't filled out.
When I'm going back to step 2 without changing anything and then again back to step 3 everything is correctly validated.

This is most likely a JS validation problem with the select fields in step 2, since this error does not occur, when I'm clicking somewhere outside of the select field after select a value before I'm moving on to step 3.

<img width="1295" alt="image" src="https://github.com/in2code-de/luxletter/assets/8640758/5e6ac1ba-faa7-413d-aa17-dbe21313e2a6">

**Comment by einpraegsam** [comment]
I just tested the latest LUXenterprise version in TYPO3 11 (Firefox and Chrome) and I could not reproduce this issue. Maybe we should talk again to each other for further investigation.

**Comment by rialDave** [comment]
I can confirm that it works correctly now on v23.0.1!
