### ISSUE TITLE
1521716628: No site found for identifier autogenerated-1

### ISSUE THREAD

**Issue by EnzephaloN** [in2code-de/luxletter#201]
Hello

When saving a newsletter, an error is thrown:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1521716628: No site found for identifier autogenerated-1-c4ca4238a0b923820dcc509a6f75849b | TYPO3\CMS\Core\Exception\SiteNotFoundException thrown in file /home/www/my.domain.org/public/typo3/sysext/core/Classes/Site/SiteFinder.php in line 102. Requested URL: https://my.domain.org/typo3/module/lux/LuxletterLuxletter?token=--AnonymizedToken--&tx_luxletter_lux_luxletterluxletter%5Baction%5D=create&tx_luxletter_lux_luxletterluxletter%5Bcontroller%5D=Newsletter`

luxletter v34.0.2
typo3 11.5.32
composer install
site-configuration-entrypoint: https://my.domain.org not /
unsubscribe-PID set to 10
template is rendered in preview

Hope you'll know how to fix...
best regards

**Comment by einpraegsam** [comment]
Just to be sure: The existing page with PID 10 is within a valid site? You can test it by checking if the Frontend of PID 10 can be rendered.

In addition: What page is using the slug `autogenerated-1-c4ca4238a0b923820dcc509a6f75849b` in your system? Is it PID 10 or a different page? And is this page also in a valid site?

**Comment by EnzephaloN** [comment]
Hello.
Page with PID 10 ist accessable and gets renderes correctly. The slug 'autogenerated...' isn't assigned to a page.

**Comment by EnzephaloN** [comment]
Found it!
In luxletter SysFolder, inside the Sender-Object. There was Seitenbaum set to "not allowed autogenerated..."
Switched to my site-config-name, should do now, if there were no other errors...
