### ISSUE TITLE
 mail queue stopps if smtp responses problems

### ISSUE THREAD

**Issue by PittRo** [in2code-de/luxletter#207]
**Typo3**: 11.5.34
**Extension**: luxletter - TYPO3 Email Marketing Newsletter Tool luxletter 19.2.2

**expected:** skipping not valid mail addresses and step to next recipient

**current behavior:** mail postings hang up, mail queue stopps

**Maillog smtp:** Thu, 25 Jan 2024 17:45:53 +0100 [ERROR] request="56e73f7177da1" , UID: 2- TransportException: Expected response code "250/251/252" but got code "450", with message "450 4.1.2 <.............@bmwi.bund.de>: Recipient address rejected: Domain not found".
Mailsserver had 50 attempts, tha it blocked luxletter

The hoster says, the blocking rule is not unusal and the tool must have a behavoir to handle this reponse.

**Comment by einpraegsam** [comment]
Can you please try the latest version of LUXletter? I think this problem should be solved.

**Comment by einpraegsam** [comment]
I re-checked this issue. And I think my answer did not match your question. There is a basic check in LUXletter that prevents that new queue entries are added for receivers with empty or invalid email address. 
Nevertheless, a mail address like `foobar@bmwi.bund.de` is a valid email address and so there is no problem in adding this as receiver to the queue.

Thinking about your problem:
1) We could add a new feature to check if the domain of the email address is registered (DNS lookup or something)
2) Maybe a bounce management could also help (see https://github.com/in2code-de/luxletter/issues/53)

But there is no final solution for the problem build in at the moment.
