### ISSUE TITLE
Invalid function request->setArguments in TYPO3 12.4.10 inside FrontendController

### ISSUE THREAD

**Issue by slavlee** [in2code-de/luxletter#208]
We have luxletter: 24.0.4 and TYPO3 12.4.10.

If we press the unsubscribe link, then an TYPO3 error occures in

FrontendController in line 163. The setArguments method does not exist anymore. 

I'm not sure, if that is the best fix. But I fixed it this way:

```
public function initializeUnsubscribe2Action(): void {

  $arguments = GeneralUtility::_GP('tx_luxletter_fe');
  
  if (is_array($arguments)) {
        //$this->request->setArguments($arguments);
        $this->request = $this->request->withArguments($arguments);
    }
}
```

Then the arguments in unsubscribe2Action are correctly initialised.

**Comment by einpraegsam** [comment]
Thx for tracking down this issue. I just pushed a fix to develop branch.
