### ISSUE TITLE
Newsletter content is double UTF-8 encoded

### ISSUE THREAD

**Issue by vistainteractive** [in2code-de/luxletter#21]
When previewing and sending newsletters containing UTF-8 content such as:
Turkish character test:
Pijamalı hasta yağız şoföre çabucak güvendi.
PİJAMALI HASTA YAĞIZ ŞOFÖRE ÇABUCAK GÜVENDİ.

The newsletter renders this text as double-encoded UTF-8 
PijamalÄ± hasta yaÄÄ±z Åoföre çabucak güvendi.
PÄ°JAMALI HASTA YAÄIZ ÅOFÖRE ÇABUCAK GÜVENDÄ°.

The page with type=1562349004 displays this text correctly, but not when it is embedded into the newsletter and rendered by the preview or mail.

**Comment by vistainteractive** [comment]
Solved.

This issue was only happening on a server with a version of Libxml < 2.7.7.

From comments in https://www.php.net/manual/en/domdocument.loadhtml.php
When using loadHTML() to process UTF-8 pages, you may meet the problem that the output of dom functions are not like the input. For example, if you want to get "Cạnh tranh", you will receive "Cáº¡nh tranh".  I suggest we use mb_convert_encoding before load UTF-8 page :
<?php
    $pageDom = new DomDocument();   
    $searchPage = mb_convert_encoding($htmlUTF8Page, 'HTML-ENTITIES', "UTF-8");
    @$pageDom->loadHTML($searchPage);

?>

Therefore wrapping the parameters passed to instances of loadHTML with mb_convert_encoding($parameter,  'HTML-ENTITIES', "UTF-8") solves the problem.

**Comment by einpraegsam** [comment]
Thx for the final feedback
