### ISSUE TITLE
Deleted FeUser leads to an 503 Error

### ISSUE THREAD

**Issue by Tim-Obert** [in2code-de/luxletter#210]
If a newsletter is sent to an user and "Rewrite links in newsletter" is enabled the link is resolving as it should. 
If the user gets deleted an exception is thrown: 
 `typo3conf/ext/luxletter/Classes/Domain/Service/LogService.php, line 42: In2code\Luxletter\Domain\Service\LogService::logNewsletterOpening(): Argument #2 ($user) must be of type In2code\Luxletter\Domain\Model\User, null given`

TYPO3 11
Version 19.2.2

**Comment by einpraegsam** [comment]
Thx for your this issue. Will be fixed with the upcoming release (maybe already today)

**Comment by einpraegsam** [comment]
Version 25.0.1 just released
