### ISSUE TITLE
{"exception":"Could not build a valid URL to unsubscribe page to pid10 in site \"mysitename\""}

### ISSUE THREAD

**Issue by EnzephaloN** [in2code-de/luxletter#212]
Using luxletter 24.0.2 in TYPO3 12.4.11
(Updated to 25.0.2 - same problem)

Added a newsletter, send to queue. Running send. 

Found in log-table:

{"exception":"Could not build a valid URL to unsubscribe page to pid10 in site \"mysitename\""}

TestEmail was send successfully. But none of the queued mails can be send.

Page10 has the unsubscribe2 Plugin

**Comment by EnzephaloN** [comment]
Hello

Sorry, but 25.0.3 does not fix this problem. Newsletter stuck, cause of "Could not build a valid URL to unsubscribe page to pid10 in site "mysitename"" error in log...

**Comment by einpraegsam** [comment]
The error is thrown here https://github.com/in2code-de/luxletter/blob/develop/Classes/Domain/Service/UnsubscribeUrlService.php#L62 - any chance to debug the exception after line 74?

**Comment by einpraegsam** [comment]
Thx, that helps a bit. Pls check if fe_users.crdate is set for the user that wants to unsubscribe.

**Comment by EnzephaloN** [comment]
Hello

Thank you for your great work and this great extension.
It's clear now, that I have to update my users. Because I've imported them into DB, there is no crdate set. 

Maybe you can add this to a "troubleshoot"-documentation...

**Comment by einpraegsam** [comment]
I will spend some time to make the errormessage better - thx for your feedback
