### ISSUE TITLE
Stop using GeneralUtility::makeInstance everywhere

### ISSUE THREAD

**Issue by georgringer** [in2code-de/luxletter#214]
Please stop using `GeneralUtility::makeInstance()` everywhere! It is only needed if

- XCLASS is allowed
- If class was not injected and injection should be used

Please don't use for stuff like creating basic objections, especially not:
- Objects for events which are final anyway!
- Models, like ` GeneralUtility::makeInstance(User::class);`

**Comment by einpraegsam** [comment]
Thx for your hints. Any real problems or simply a small rant?

**Comment by einpraegsam** [comment]
I guess not. I will consider using more DI even if this is often a pain. Nevertheless, there is nothing to do for the moment. It is more a general task.

**Comment by georgringer** [comment]
it is not a rant, but saw it because phpstorm told me about some warnings

<img width="796" alt="Bildschirmfoto 2024-03-06 um 15 42 57" src="https://github.com/in2code-de/luxletter/assets/1905663/4df75818-3707-444d-afab-1dda42757fe5">

and it is smaller to read
```
        $event = $this->eventDispatcher->dispatch(
            new NewsletterParseSubjectEvent($subject, $properties)
        );
```
