### ISSUE TITLE
Call to a member function getRemoteAddress() on null on ./vendor/bin/typo3 luxletter:queue 

### ISSUE THREAD

**Issue by Abdul-Hafiz** [in2code-de/luxletter#219]
Hi There,

I have TYPO3 12.x with latest EXT:lux and EXT:luxletter.
Scheduler from TYPO3 BE for luxletter:queue works fine.

But when I set cron it throws error
`Uncaught TYPO3 Exception Call to a member function getRemoteAddress() on null thrown in file/vendor/typo3/cms-core/Classes/ExpressionLanguage/FunctionsProvider/DefaultFunctionsProvider.php in line 75
`
I have tried from ssh/terminal with `./vendor/bin/typo3 luxletter:queue` still it shows the same error.

Can any one help what could be the problem or how can I fix this?

Thanks for time!

**Comment by einpraegsam** [comment]
Thx, as I just wrote you in slack:
```
To help you, I would need the full backtrace of this error. Because getRemoteAddress is not a function within LUXletter, I need the function in LUXletter that could cause this issue.
```

**Comment by Abdul-Hafiz** [comment]
Hi @einpraegsam 

 It was issue with TypoScript  condition
[ip("devIP")]
So I have removed it as it was not needed.
And it works okay.

Sorry to disturb you with the bug.

Thanks for the reply BTW.

Best regards

**Comment by einpraegsam** [comment]
Thx for your feedback, I'm going to close this issue
