### ISSUE TITLE
Feature request: Personalize email To: 

### ISSUE THREAD

**Issue by vistainteractive** [in2code-de/luxletter#22]
In In2code\Luxletter\Mail\SendMail, replace 'Newsletter receiver' in setTo with the user.firstName user.lastName

$mailMessage
            ->setTo([$email => 'Newsletter receiver'])

**Comment by einpraegsam** [comment]
Done in develop branch. Will be released with the upcoming version.
Now with "Lastname, Firstname" instead of "Newsletter receiver"
