### ISSUE TITLE
[BUGFIX] Passthrough real exception

### ISSUE THREAD

**Issue by julianhofmann** [in2code-de/luxletter#221]
If NewsletterUrl::getContentFromOrigin() fails to read the newsletter via Core/GuzzleClient, this is acknowledged with an Exception that only deals with the type definition and missing TypoScript. A failure of the HTTP connection (e.g. also due to an invalid SSL certificate) is not yet mentioned.

This can be confusing when troubleshooting.

If a RequestException is thrown, then this should also be passed on instead of (incorrectly) relabeling it as a MisconfigurationException and throwing it.

**Comment by einpraegsam** [comment]
Just merged
