### ISSUE TITLE
Not Composer Install

### ISSUE THREAD

**Issue by marexx** [in2code-de/luxletter#223]
I know i'm supposed to use the composer install, 
but in this case it wasn't possible.
I Installed it old school, also the css-to-inline-styles.
And it seems to work, I can create newsletters... also send the testmail.
but the newsletter itself doesn't get send. I created a scheduler: luxletter:queue 50 0
am i missing something?

**Comment by einpraegsam** [comment]
I have no clue and due to a no-composer installation I can't give any feedback, because I simply don't have any.

**Comment by marexx** [comment]
I switched to composer Mode. But still the same. Can Send the testmail but not the real newsletter.
