### ISSUE TITLE
Dashboard Filter Sites does not show any labels

### ISSUE THREAD

**Issue by magicHatOfTYPO3** [in2code-de/luxletter#224]
In the Luxletter (26.1.0) Dashboard  the dropdown of the sites filter is populated with values (and it is functional), but the labels are missing. 

![luxletter-sites-filter](https://github.com/user-attachments/assets/86ba1e40-f1b1-4342-a9eb-ddce2d08e7bb)

**Comment by einpraegsam** [comment]
Hi, I guess the value "websiteTitle" is emtpy or not set in your site configuration - right?

**Comment by magicHatOfTYPO3** [comment]
confirm. If I set websiteTitle in config.yaml the label is shown.

Thanks for clarify this! :)

**Comment by einpraegsam** [comment]
Nevertheless, maybe it is a relevant case. Some installations keep websiteTitle empty because they don't want a title postfix "page | websiteTitle". Maybe we need a fallback for the label?

**Comment by magicHatOfTYPO3** [comment]
The "identifier" might be a candidate for that, as it is set for any site configuration for sure.

**Comment by einpraegsam** [comment]
Thx, I will provide a fix within the next days

**Comment by einpraegsam** [comment]
I just release version 26.2.0 with a small fix. We are using now site.identifier instead of websiteTitle even if identifier could be meaningless in some smaller installations.
