### ISSUE TITLE
tt_content-CType=news_newsdetail not yet supported

### ISSUE THREAD

**Issue by linawolf** [in2code-de/luxletter#226]
Updated a project from TYPO3 v11.5 to 12.4 using ext:luxletter and ext:news.

When displaying a newsletter in the backend module or opening it with its type I get the following error:

![image](https://github.com/user-attachments/assets/1d38ad0c-cba1-472d-aff6-5a35aecf44af)
****

I can resolve it with overriding the template `Generic.html` as follows:

```
<f:if condition="{data.CType} == news_newsdetail">
    <f:then>
        <f:cObject typoscriptObjectPath="tt_content.news_newsdetail.20" data="{data}" table="tt_content" />
    </f:then>
    <f:else>
        <f:render partial="NotYetSupported" arguments="{_all}"/>
    </f:else>
</f:if>
```

But I think it should be supported out-of-the-box

**Comment by linawolf** [comment]
You supported it implicitly as news only had one plugin before. After discontinuing switschable controller actions they were split up in 5 or so plugins none of which is currently supported by Luxletter

**Comment by einpraegsam** [comment]
I digged into this issue and saw, that the best way to solve this issue would to extend 
```
tt_content {
  news_pi1.templateName = NewsList
  news_newsliststicky.templateName = NewsList
  news_newsselectedlist.templateName = NewsList
  news_newsdetail = NewsDetail
}
```
with  complete new template file for the detail view. This would then need a template in `EXT:luxletter/Resources/Private/FluidStyledMailContent/Templates/NewsDetail.html`

---

Nevertheless, there is no table based rendering for the news detail view. And if we would support the news detail page out of the box, we also have to add a table based rendering for newsletters. But this needs a bit more effort...

---

So, for now, I tend to keep the current status. If someone needs to render the news-detail view, he should do it manually.

Thx for the report and patience

**Comment by linawolf** [comment]
I think it would be nice to add this kind of information to the docs. As until the update it was possible to display single news when providing your own template and now it is not.

The template for news is really a news template not a tt_content template where ttt_content only loads the plugin...
