### ISSUE TITLE
Table 'database.tx_luxletter_domain_model_user' doesn't exist

### ISSUE THREAD

**Issue by grosswerner** [in2code-de/luxletter#24]
Hello,

I am using Typo3 9.5.15 and the newest version of Luxletter.

For my newsletter I created a separate page on my website. In the newsletter are different "Teaser" elements, which get shortened so that the recipient can click on "Read more.." to get directed to the website so read more.

This function works properly once i send out the newsletter. After a few hours it suddenly doesn't work anymore though. If the newsletter recipient clicks on "Read more.." after a while the page is not available anymore.

In my backend log file I receive the following error message:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1472074485: Table 'db285520_4.tx_luxletter_domain_model_user' doesn't exist | TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException thrown in file /kunden/285520_91189/lts9/typo3_src-9.5.15/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbBackend.php in line 375. Requested URL: https://www.rohr-evangelisch.de/?luxletterlink=54da1445c9d016b0bf3401d155b223f0ae71ccec91e929ddaeef389cd584fef4 

If i delete the Typo3temp folder and delete the Typo3 front and backend cache the link works again.

Does anyone have an idea what causes this error?

**Comment by einpraegsam** [comment]
Hmm, this sounds a bit strange. Are you using any cache extensions like static_filecache or a proxy or similar stuff?

**Comment by grosswerner** [comment]
No, i don't use any cache extensions like static_filecache. The server is is hosted on domainfactory and I am not aware about any proxies.

I've also gotten one error message which is similiar to the one above, but doesn't say:
tx_luxletter_domain_model_user
but:
tx_luxletter_domain_model_usergroup(s?)

**Comment by einpraegsam** [comment]
Ok, I re-read the error message. This message comes up when the TypoScript could not be loaded and the mapping of the tables is missing. While TYPO3 10 does this in a much better way, TYPO3 9 uses TypoScript for this task.

Please add this lines of TypoScript to your root template:
```config.tx_extbase {
    persistence {
        classes {
            In2code\Luxletter\Domain\Model\User {
                mapping {
                    tableName = fe_users
                }
            }
            In2code\Luxletter\Domain\Model\Usergroup {
                mapping {
                    tableName = fe_groups
                }
            }
        }
    }
}```

And give feedback

**Comment by grosswerner** [comment]
I inserted the TypoScript snippet into the setup of root using copy and paste around 16:00, unfortunately the problem is not solved. 

In the backend log the following message appears again at 20:30

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1472074485: Table 'db285520_4.tx_luxletter_domain_model_usergroup' doesn't exist | TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException thrown in file /kunden/285520_91189/lts9/typo3_src-9.5.15/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbBackend.php in line 375. Requested URL: https://www.rohr-evangelisch.de/?luxletterlink=67820829ec340c7f09df1dd3582ea456434adc8df7d52986dbb32fdffeaa7b03 

In the frontend the following message appears after I click the link in the mail again

Oops, an error occurred!
Table 'db285520_4.tx_luxletter_domain_model_usergroup' doesn't exist

More information regarding this error might be available online.

**Comment by einpraegsam** [comment]
This is a bit strange. Can you please make a screenshot of your first and second level pages in pagetree from backend to get a feeling how many pages you have in which orderings.

**Comment by grosswerner** [comment]
A screenshot of my first and second level pages

![NewsletterScreenshot](https://user-images.githubusercontent.com/63292578/78774730-63d1c000-7995-11ea-86a1-d14fd32dd681.png)

**Comment by einpraegsam** [comment]
I'm running out of ideas for TYPO3 9. This error should not happen and is more related to Extbase and TYPO3 in general.

**Comment by elvis394** [comment]
@einpraegsam  I ran into the same issue with your extension in TYPO3 9. My guess is, that the table mapping isn't loaded when the Middleware is called. You might have to get it with an raw SQL query to avoid this problem.

**Comment by einpraegsam** [comment]
That is not that easy to rewrite. Did anyone open a ticket on forge.typo3.org that describes the missing mapping configuration for cached calls in PSR-15? 
Can anyone confirm or decline that the error is gone in TYPO3 10?

**Comment by einpraegsam** [comment]
I have read of a possible solution. Can someone please test and add those lines:
```
$cacheManager = GeneralUtility::makeInstance(\TYPO3\CMS\Core\Cache\CacheManager::class);
            GeneralUtility::makeInstance(
                \TYPO3\CMS\Extbase\Persistence\ClassesConfigurationFactory::class, $cacheManager
            )->createClassesConfiguration();
```
At the beginning of \In2code\Luxletter\Middleware\LuxletterLink::process() and test for me?

**Comment by elvis394** [comment]
This is something that would only work in TYPO3 10, because the ClassesConfigurationFactory isn't avaliable in TYPO3 9

**Comment by einpraegsam** [comment]
Ok, another hints from Alexander Schnitzler:
```Well, since the mapping is typoscript in 9 you have to make sure that you have a fully functional frontend i.e. your middleware has to be called quite late in the stack. If you need it very early you have to setup TSFE manually just like you would do in an eID script.```

So following the first tipp is to change the sorting. Can anyone test if it helps to change the file `Configuration/RequestMiddlewares.php` in line 7 to `typo3/cms-frontend/tsfe`?

**Comment by elvis394** [comment]
It works! :-)

**Comment by einpraegsam** [comment]
Pushed to develop branch. But because some people had this annoying problem, I will release a 2.2.2 in a few minutes.
