### ISSUE TITLE
wrong template used in newsletter because of sorting problem

### ISSUE THREAD

**Issue by dirnbauer** [in2code-de/luxletter#26]
It seems that there is a problem with sorting of $templateRootPaths (TYPO3 LTS 9.5.15):

https://github.com/in2code-de/luxletter/blob/5a375c62952bd9eb06aad03ac71629eada12e40f/Classes/Utility/TemplateUtility.php#L25

In my debugging-example at the end the highest number (10) should be returned as first element of the array `EXT:theme/Resources/Private/Extensions/Newsletter/Templates/`

debug `$templateRootPaths` returns my TS-setttings:
https://github.com/in2code-de/luxletter/blob/5a375c62952bd9eb06aad03ac71629eada12e40f/Classes/Utility/TemplateUtility.php#L24

```
   10 => 'EXT:theme/Resources/Private/Extensions/Newsletter/Templates/' (60 chars)
   0 => 'EXT:luxletter/Resources/Private/Templates/' (42 chars)
   1 => 'EXT:lux/Resources/Private/Templates/' (36 chars)
```
   
debug   `array_reverse($templateRootPaths)` with `array_reverse` in line 25 results:  
```
   0 => 'EXT:lux/Resources/Private/Templates/' (36 chars)
   1 => 'EXT:luxletter/Resources/Private/Templates/' (42 chars)
   2 => 'EXT:theme/Resources/Private/Extensions/Newsletter/Templates/' (60 chars)
```
   

debug $templateRootPaths (after **krsort($templateRootPaths)**; and **without array_reverse)** returns correct result (returns value of 10):

```php
$templateRootPaths = ConfigurationUtility::getExtensionSettings()['view']['templateRootPaths'];
krsort($templateRootPaths);
foreach ($templateRootPaths as $rootPath) {
```
```
   10 => 'EXT:theme/Resources/Private/Extensions/Newsletter/Templates/' (60 chars)
   1 => 'EXT:lux/Resources/Private/Templates/' (36 chars)
   0 => 'EXT:luxletter/Resources/Private/Templates/' (42 chars)   
```

I can create a pull request if you want to. But maybe it is better to do this sorting somewhere else?
And thank you very much for this great extension!

**Comment by einpraegsam** [comment]
Thx, please describe how I could reproduce the issue on my testsystem

**Comment by reiherm** [comment]
1. override your NL template eg. (templateRootPaths.2 = EXT:your_base_project_extension/Resources/Extensions/luxletter/Templates/) in another extension
2. save and send a NL (not only preview or test)
3. the TemplateUtility.php now takes the wrong templateRootPaths because of your ext_typoscript_setup.txt the order is lux, luxletter and then EXT:your_base_project_extension (EXT:your_base_project_extension should be first because you want to overwrite the default luxletter template)

**Comment by dirnbauer** [comment]
I hope the description of @reiherm is helpful. if not please leave a messge. thanks!

**Comment by einpraegsam** [comment]
I just tested with this TypoScript:
```
module {
    tx_luxletter {
        view {
            templateRootPaths {
                0 = EXT:luxletter/Resources/Private/Templates/
                1 = EXT:lux/Resources/Private/Templates/
                2 = fileadmin/templates/
            }
        }
    }
}
```

While I placed a file at `fileadmin/templates/Mail/NewsletterContainer.html` with a Hello World inside. After that, I debugged in `TemplateUtility::getExistingFilePathOfTemplateFileByName` the variable `array_reverse($templateRootPaths)`, go to the backend module, added a new newsletter and pressed "save".

The result is:
```
array(3 items)
   0 => 'fileadmin/templates/' (20 chars)
   1 => 'EXT:lux/Resources/Private/Templates/' (36 chars)
   2 => 'EXT:luxletter/Resources/Private/Templates/' (42 chars)
```

So far, this is correct in my eyes. Now I will also test the newsletter sending.
After saving the newsletter (Dumytext "Test Test" in the NewsletterContainer.html) also a db statement results in the correct text:

```
+-----+-----+----------------------------------+------------+
| uid | pid | subject                          | bodytext   |
+-----+-----+----------------------------------+------------+
|   6 |   1 | Your personell newsletter 2020/1 | Test Test
 |
+-----+-----+----------------------------------+------------+
```

And at the end when I start to work the queue and a mail is send (and catched with mailhog) also the mail template is correct. Please tell me what I did wrong.

![screenshot-127 0 0 1_8025-2020 04 22-12_45_06](https://user-images.githubusercontent.com/89055/79973012-1e35ec80-8497-11ea-9121-29ce48b894e9.png)
![screenshot-lux-t310 localhost de-2020 04 22-12_30_12](https://user-images.githubusercontent.com/89055/79973014-1ece8300-8497-11ea-8985-fdd6b3c69d68.png)

**Comment by dirnbauer** [comment]
If you add the settings in the SAME TS-Template-Record - no problem.
But if you split the settings to another (included) ts-Template, the array has a wrong order.

we use a sitepackage (theme).
In **ext:theme** we add a TS-template with another entry for templateRootPaths

```
module {
    tx_luxletter {
        view {
            templateRootPaths {
                10 = EXT:theme/Resources/Private/Extensions/Newsletter/Templates/
            }
        }
    }
}
```
Object browser:

![objectbrowser](https://user-images.githubusercontent.com/16100986/79979690-34957580-84a2-11ea-918f-fefcb469ca42.png)

Template-analyzer:
![template_analyzer](https://user-images.githubusercontent.com/16100986/79979806-66a6d780-84a2-11ea-9c7c-03bf8d8ebc68.png)

Debug $templateRootPaths
```php
  $templateRootPaths = ConfigurationUtility::getExtensionSettings()['view']
```

```
array(3 items)
   10 => 'EXT:theme/Resources/Private/Extensions/Newsletter/Templates/' (60 chars)
   0 => 'EXT:luxletter/Resources/Private/Templates/' (42 chars)
   1 => 'EXT:lux/Resources/Private/Templates/' (36 chars)
```


at the end:
```php
$templateRootPaths = ConfigurationUtility::getExtensionSettings()['view']['templateRootPaths'];
\TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump(array_reverse($templateRootPaths));
```

wrong template (first element of array)  is used (0 => 'EXT:lux/Resources/Private/Templates/' )

```
array(3 items)
   0 => 'EXT:lux/Resources/Private/Templates/' (36 chars)
   1 => 'EXT:luxletter/Resources/Private/Templates/' (42 chars)
   2 => 'EXT:theme/Resources/Private/Extensions/Newsletter/Templates/' (60 chars)
```

**Comment by einpraegsam** [comment]
Ah, ok, so your TypoScript is added before Luxletter add its TypoScript - so a quickfix for you would be to fix the TypoScript Ordering Problem?
Nevertheless, I think you are basicly right with your pull request.

**Comment by dirnbauer** [comment]
> Ah, ok, so your TypoScript is added before Luxletter add its TypoScript

exactly.

> - so a quickfix for you would be to fix the TypoScript Ordering Problem?

yes. 

> Nevertheless, I think you are basicly right with your pull request.

Thanks for your great help!

**Comment by einpraegsam** [comment]
Will be released with the upcoming version
