### ISSUE TITLE
Images not shown in email

### ISSUE THREAD

**Issue by mmirsch** [in2code-de/luxletter#28]
When sending newsletters, images inside the body are not visible because image-urls are relative.
Is there an option to use absolute URLs für images?
Or is there an option to embed images directly inside the email?

Thanks and greetings,
Manfred Mirsch

**Comment by einpraegsam** [comment]
That should not happen, Image URL should be absolute (I just tested again and everything works as expected). The domain is prefixed here: https://github.com/in2code-de/luxletter/blob/develop/ext_localconf.php#L34

What if you check your TypoScript Object Browser when searching for variable `fluidStyledMailContent.config.absRefPrefix`

Should look similar to:
![screenshot-lux-t310 localhost de-2020 04 25-12_45_57](https://user-images.githubusercontent.com/89055/80277957-e5924f00-86f2-11ea-988c-397677519465.png)
?

**Comment by mmirsch** [comment]
My mistake was, that I didn't set "config.absRefPrefix".
After doing this, links are absolute.

Also for using FluidStyledMailContent I had to add the type configgurations in my site-cofiguration (config.yaml).
Now everything works very well.

**Comment by einpraegsam** [comment]
I just added a question to FAQ in documentation for people with similar problems

**Comment by mmirsch** [comment]
Thanks for help and for this great plugin,
Manfred
