### ISSUE TITLE
[IDEA] Add authentication in ParseNewsletterUrlService

### ISSUE THREAD

**Issue by AnatolePiveteau** [in2code-de/luxletter#3]
Hello,

Thank you for this new extension.

I begin to use your extension on an intranet protected by authentication, but when i came on the step "send test mail & preview" the preview is not loaded (401 Unauthorized).

Now it work for me but I did it the wrong way. 
It is in file Classes/Domain/Service/ParseNewsletterUrlService.php at line 137

```
    protected function getContentFromOrigin(User $user): string
    {
        if ($this->url === '') {
            throw new \LogicException('Given URL was invalid and was not parsed', 1560709687);
        }
        //$string = GeneralUtility::getUrl($this->url);
	$url = str_replace("//", "//USERNAME:PASSWORD@", $this->url);
	$string = file_get_contents($url);
        $string = $this->getBodyFromHtml($string);
        if ($string === false) {
            throw new \DomainException('Given URL could not be parsed and accessed', 1560709791);
        }
        if ($this->isParsingActive()) {
            $parseService = ObjectUtility::getObjectManager()->get(ParseNewsletterService::class);
            $string = $parseService->parseMailText($string, ['user' => $user]);
        }
        $this->signalDispatch(__CLASS__, __FUNCTION__, [$string, $user, $this]);
        return $string;
    }
```

I think it can be a good feature,

Best Regards,

Anatole PIVETEAU

**Comment by einpraegsam** [comment]
Thx for your comment.
Maybe this is a feature for later.
I will let this ticket open now. Maybe others also need the feature to parse authentication needed content. 

BTW: We could quickly add a signal in getContentFromOrigin to allow you to hook into the code if wanted?

**Comment by AnatolePiveteau** [comment]
Thanks for answer,
Yes, It might be a great solution for moment !

**Comment by einpraegsam** [comment]
Thx, I added another signal. In this case in https://github.com/in2code-de/luxletter/blob/develop/Classes/Domain/Service/ParseNewsletterUrlService.php#L69 to modify the class property url.
Now I would close this issue for the moment. Maybe we add authentification later if this feature is also needed from others.
