### ISSUE TITLE
Error "Table 'd031023e.tx_luxletter_domain_model_usergroup' doesn't exist" in 2.2.0

### ISSUE THREAD

**Issue by stephangrass** [in2code-de/luxletter#30]
Hi,
we also sometimes get the error "Table 'd031023e.tx_luxletter_domain_model_usergroup' doesn't exist" in version 2.2.0 under TYPO3 9 when clicking links in the newsletter. 

But not always. Clearing the cache (all caches) temporarily fixes the problem.

We also added the TypoScript from issue #24 to the root template. Everything seems ok, but after a while the error reappears.

Where's the problem?

**Comment by stephangrass** [comment]
In Version 2.2.0 on TER still stands in the Configuration/RequestMiddlewares.php 

`'typo3/cms-frontend/timetracker'`

I add  'typo3/cms-frontend/tsfe' manually. Let's see, if it works ...

**Comment by stephangrass** [comment]
... The error still occures ...

**Comment by einpraegsam** [comment]
Can you please post your Middleware Orderings? Go into backend and use the "configuration" backend module. Change the select to "PSR-15 Middlewares" and open the frontend middlewares.

**Comment by stephangrass** [comment]
OK

![2020-06-08_09-28-46](https://user-images.githubusercontent.com/4489147/84003522-77d07880-a96a-11ea-84f7-80ae2ec605c2.png)

**Comment by einpraegsam** [comment]
Hmm, luxletterlink is nearly the latest - so if it is still not working in TYPO3 9, I don't see a solution at the moment.
Maybe you have to turn off the click-tracking-feature in the extension settings.

**Comment by stephangrass** [comment]
Thanks.
So I will/must update to 10.4.

**Comment by einpraegsam** [comment]
Sorry, if this bug is still valid - even after https://github.com/in2code-de/luxletter/issues/24 in TYPO3 9.5 I don't see any solutions near:
* Upgrading to TYPO3 10 or
* Disabling the link tracking feature in Extension Manager settings

**Comment by rr-it** [comment]
Quick and super dirty hack for TYPO3 9:

``` sql
CREATE VIEW `tx_luxletter_domain_model_usergroup` AS SELECT * FROM `fe_groups`;
CREATE VIEW `tx_luxletter_domain_model_user` AS SELECT * FROM `fe_users`;
```
Underlying issue:
https://forge.typo3.org/issues/75399
