### ISSUE TITLE
Plain version of the Newsletter

### ISSUE THREAD

**Issue by Xippo** [in2code-de/luxletter#32]
Is there out of the box a feature to send the newsletter also in a plain version? I found anything about that.

**Comment by einpraegsam** [comment]
No, not at the moment

**Comment by Xippo** [comment]
Would it be ok if we develop this feature and we add it over a PR? Technically we should archive this in the same way like you do, we can render the plain version over a different pagetype or would you suggest a different approach?

**Comment by einpraegsam** [comment]
Sure :)
