### ISSUE TITLE
Strange display problem in the backend module in TYPO3 10

### ISSUE THREAD

**Issue by stephangrass** [in2code-de/luxletter#33]
Hi. There are display problems in the backend module in TYPO3 10.

The head area covers important elements such as the "new newsletter" button:

![2020-06-16_13-32-22](https://user-images.githubusercontent.com/4489147/84769421-18134680-afd6-11ea-82d2-d032afb43a32.png)
![2020-06-16_13-32-14](https://user-images.githubusercontent.com/4489147/84769425-19dd0a00-afd6-11ea-94db-68e02fcf9b69.png)

**Comment by einpraegsam** [comment]
Please write the specific version of TYPO3 and luxletter.
This problem is probably related to Revision d27a62054b8b5efc434834cd540e4b792878ba9f

**Comment by stephangrass** [comment]
OK. Thanks.
TYPO3 10.4.4
Luxletter 2.2.0

**Comment by einpraegsam** [comment]
I just tested and don't have the described problem.

1) Do you have browser-caching issues? Can you please try again with opened browser console and "disabled caches" in Tab "Network"?

2) Beside this: If you inspect the HTML of the right iframe - do you have such an element (with the class module-body):
```
<div class="lux-backend module-body">...
```

3) What OS and browser do you use?

**Comment by stephangrass** [comment]
Hi,
in 2.2.0 from TER in the Backend.html I still found

`<div class="lux-backend{luxletter:condition.isVersionToCompareSameOrLowerThenCurrentTypo3Version(version:'10.0.0',else:' module-body')}">`

Changing to `<div class="lux-backend module-body">` helps.

Thanks

**Comment by einpraegsam** [comment]
Using 2.3.0 from packagist via composer helps. Thx
