### ISSUE TITLE
fluidStyledMailContent.config.absRefPrefix shows wrong URL

### ISSUE THREAD

**Issue by taunusweb** [in2code-de/luxletter#35]
I have a strange Problem with "fluidStyledMailContent.config.absRefPrefix", I changed my base url in sites/config.yaml, but that has no effect, even if I set it directly in my TS Setup `fluidStyledMailContent.config.absRefPrefix = https://www.xxxde/` 
In the Newsletter Module I get the following error:
`Origin [uid] could not be converted into a valid url!
Message: Given URL could not be parsed and accessed (Tried to read url: http://updatexxx.de/`

**Comment by danaron** [comment]
Hi taunusweb,
I do have the same problem. The preview with the variable &type=1562349004 is shown OK, but preview gives me the same error. Have you find a solution time beeing?
Thanks for your answer.
Best regadrs danaron

**Comment by danaron** [comment]
I was on a staging server and switched to the real URL today and like a miracle, all works!
Thanks to the developers from in2code. It is a nice extension and works well!
Have a nice weekend!

**Comment by einpraegsam** [comment]
Is the problem still existing? @taunusweb

**Comment by taunusweb** [comment]
Thanks at all, yesterday I was workin' on that topic again, and what should I say: it works!
