### ISSUE TITLE
Special character problem after updating to TYPO3 10

### ISSUE THREAD

**Issue by stephangrass** [in2code-de/luxletter#36]
After updating to TYPO3 10 by using luxletter 2.3.0 the special characters are displayed incorrectly in Outlook. The mail built in uft-8  will be send with charset ISO 8859-1.

How can I change this?

![2020-06-19_11-50-55](https://user-images.githubusercontent.com/4489147/85120349-6bc69f80-b223-11ea-837f-07bc5f9e7f7c.png)

**Comment by stephangrass** [comment]
Solution:

In SendMail.php, function send() in line 86 the charset is set to text/html

`            ->html($this->bodytext, 'text/html');`

must be changed to 

`            ->html($this->bodytext);`

and it will worked (utf-8 is the default charset).

**Comment by einpraegsam** [comment]
Thx for digging into it. I pushed a fix to develop branch.
