### ISSUE TITLE
Problems when changing the template path

### ISSUE THREAD

**Issue by dhuettner** [in2code-de/luxletter#37]
after I changed the path to the template and try to load my own template. the extension does not let me send test mails anymore and throws me back a 500 error code:
Look like this
```
VM32046 Module.min.js:1 
POST https://myurl/typo3/index.php?route=%2Fajax%2Fluxletter%2FtestMail&token=234e6878f35d8bc61b037d86bd0d262e6e4e252e&origin=46&email=unsereagentur%40gmail.com&subject=test 
500
```
The only file I have changed is the NewsletterContainer.html
and here my typoscript
```
plugin {
    tx_luxletter_fe {
        view {
            templateRootPaths {
                10 = EXT:mystag/Resources/Private/EXT/luxletter/Templates/
            }
        }
    }
}
module {
    tx_luxletter {
        view {
            templateRootPaths {
                10 = EXT:mystag/Resources/Private/EXT/luxletter/Templates/
            }
        }
    }
}
```

**Comment by dhuettner** [comment]
Okay, I found the problem. In my NewsletterContainer.html I have installed Typoscript. If I remove this, the sending goes as well. But is it possible to include Typoscript in the future?

**Comment by einpraegsam** [comment]
What does `I have installed Typoscript` mean?

**Comment by dhuettner** [comment]
installiert = inkludiert
Ich habe versucht mit hilfe von Typoscript den Footer bereich auszulagern wollen. 

`<f:cObject typoscriptObjectPath="lib.footerNewsletter" />`

und dazu folgendes benutzt_


```
lib{
    footerNewsletter = CONTENT
    footerNewsletter{
        table = tt_content
        select {
            orderBy = sorting
            where.field = colPos
            where.intval = 1
            where.wrap = colPos=|
            languageField = sys_language_uid
            pidInList = 81
        }
   }
}
```

**Comment by einpraegsam** [comment]
Hi,

I just tested with this TypoScript in the main Template:

```
lib.test = TEXT
lib.test.value = Hello World
```

And with 
`<f:cObject typoscriptObjectPath="lib.test">test</f:cObject>`

without problems. Can you confirm that this test example also works for you?

**Comment by dhuettner** [comment]
Yes this works

Am Mi., 1. Juli 2020 um 10:51 Uhr schrieb Alex Kellner <
notifications@github.com>:

**Comment by froemken** [comment]
This PR may solve that problem, too: https://github.com/in2code-de/luxletter/pull/46

Working with TS `data` and other cObjects needs `cObjectDepthCounter` of TSFE, but as long as TSFE is not loaded in BE nor in scheduler, this will result in an Exception: accessing `cObjectDepthCounter` on NULL.

Stefan

**Comment by einpraegsam** [comment]
Does the pr from Stefan Frömken help in this case?

**Comment by einpraegsam** [comment]
I will close this issue for now.
If someone needs help to change the Templates, see #70
