### ISSUE TITLE
Problems with incl. unsubscribe plugin

### ISSUE THREAD

**Issue by efact007** [in2code-de/luxletter#41]
TYPO3 10.4.8
PHP 7.2.32
Have problems with the incl. unsubscribe plugin
got Message "User invalid" An error occured. Please try again later.

fe_user_group and fe_user are set as described

**Comment by einpraegsam** [comment]
Sorry, but that doesn't help me. Please can you paste the generated link?

**Comment by efact007** [comment]
https://www.greiner-aerospace.com/unsubscribe/

**Comment by einpraegsam** [comment]
This can't be the correct link without any parameters like newsletter or user - is this really the link that is generated in your emails?

**Comment by efact007** [comment]
Sorry, my fault, everything is perfect
