### ISSUE TITLE
Allow BE Users to send a testmail again

### ISSUE THREAD

**Issue by froemken** [in2code-de/luxletter#42]
Hello,

currently you set email fields to send a testmail to display:none;
So, if I want to re-send a testmail, maybe, to another person, I have to re-build the same newsletter again from scratch.

Would be cool, if you do not hide this email field.

And could you please use official notification JS API of TYPO3 to inform BE Users that mail was sent?

Add `"TYPO3/CMS/Backend/Notification"` to define on top and then within your callback:

```
this.testMailListenerCallback = function (e) {
    var headerElement = document.querySelector('[data-luxletter-testmail="testmail-header"]');
    var messageElement = document.querySelector('[data-luxletter-testmail="testmail-message"]');
    if (headerElement !== null && messageElement !== null) {
        notification.success(
            headerElement.getAttribute("data-luxletter-testmail-title"),
            messageElement.getAttribute("data-luxletter-testmail-message")
        );
    }
}
```

Sorry, I just don't have a minifier here, so I can't create a PR for you.

Nice greetings

Stefan

**Comment by einpraegsam** [comment]
Testmails can be send multiple times in 4.0 now.
