### ISSUE TITLE
Feature: import recipients

### ISSUE THREAD

**Issue by webian** [in2code-de/luxletter#54]
A module to import recipients from a csv.

The user uploads a csv file and the system analyzes it and proposes fields that allow the user to map the csv data with those of the DB.

The user has these possibilities:
- choose the page/folder where to import the data
- delete all addresses in the folder before importing
- select the csv field delimiters
- whether or not to update existing recipients

The system also reports duplicate addresses.

**Comment by einpraegsam** [comment]
Thx, but this will not be part of the extension in future to keep it simple.
