### ISSUE TITLE
URL could not be parsed and accessed

### ISSUE THREAD

**Issue by roccoh** [in2code-de/luxletter#55]
Creating a new Newsletter leads to the following result:
Result: Origin 102 could not be converted into a valid url!
Message: Given URL could not be parsed and accessed (Tried to read url: https://www.domain.org/newsletter-09-2020/newsletter.html?). Typenum definition in site-configuration not set? Fluid Styled Mail Content TypoScript added?

My settings:
_ fresh TYPO3 10.4.8 installation width composer
_ URL defined: in config.yaml and ext_conf_template.txt (both are the same)
_ Typenum definition in site-configuration is set (as described in the instructions for TYPO3 9)
_ Fluid Styled Mail Content TypoScript is added

What am I doing wrong?

**Comment by froemken** [comment]
Hello @roccoh 

you have forgotten to set the domain in Extension Settings of EXT:luxletter.

Stefan

**Comment by roccoh** [comment]
Hello Stefan
Many thanks for the hint.
I don't know why I could miss this – its clear described in your manual(!)...

But I have still a problem:
in my page config.yaml I have the following addition as described for TYPO3 9, but I guess it should be the same for TYPO3 10

routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    index: ''
    suffix: /
    map:
      newsletter.html: 1562349004

The output is now:
Tried to read url: kristall10.test/newsletter-09-2020/newsletter.html?
As you see, the part "kristall10.test/newsletter-09-2020" is correct
The FE Template for this page is "Newsletter.html"

For my defense: it's the first time I am working with luxletter and composer and I'm embarrassed that I can't find out, what's wrong.

Can you please help me?

**Comment by froemken** [comment]
Hello @roccoh 

`In your manual` hihi. Sorry, I'm not a developer nor employee of luxletter ;-) I only have invested much time into luxletter.

Yes, you need the mapping to pageType 1562349004 in TYPO3 10, too.

The URL `kristall10.test/newsletter-09-2020/newsletter.html` looks pretty good. So pageType 1562349004 was applied successfully.

Composer is not your problem.

I don't understand: `The FE Template for this page is "Newsletter.html"`

`Can you please help me?` With what? You only have written what you have done, but you don't have written a question nor explained a problem.

Stefan

**Comment by roccoh** [comment]
Hello Stefan
Many thanks for help. I see, it was a bit confusing ;-).
My problem is, that i cannot create a preview of the newsletter.

Result: Origin 102 could not be converted into a valid url!
Message: Given URL could not be parsed and accessed (Tried to read url: https://kristall10.test//newsletter-09-2020/newsletter.html?). Typenum definition in site-configuration not set? Fluid Styled Mail Content TypoScript added?

Typenum is set in sites config.yaml
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    index: ''
    suffix: /
    map:
      preview.html: 1560777975
      newsletter.html: 1562349004
      pixel.png: 1561894816
 Fluid Styled Mail Content TypoScript is also added

Any help would be appreciated.

**Comment by froemken** [comment]
Hello @roccoh 

can you please check, if the configured scheme and domain of luxletter extension-settings matches exactly the scheme and domain in TYPO3 sites module?
Further I wonder about the double slashes in your URL. Do you really need the suffix in your sites configuration?
And why do you have a questionmark at the end of your URL?

Stefan

**Comment by roccoh** [comment]
Many thanks Stefan

The domain scheme was without http://
Now i can work width it.
I'm so stupid... Sorry for that.
