### ISSUE TITLE
No typenum is addet to the page url

### ISSUE THREAD

**Issue by roccoh** [in2code-de/luxletter#57]
I know it's not a issue of the extension, but I'm too ignorant to see what I'm doing wrong.

I added the following to my site config.yaml:
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    index: ''
    suffix: /
    map:
      preview.html: 1560777975
      newsletter.html: 1562349004
      pixel.png: 1561894816
	  
The url for the site is correct. But no typenum is addet to the page url.
Therefore it ends allways width the error message: Origin 102 (pid of the Newsletter) could not be converted into a valid url!
The url looks like this: kristall10.test/newsletter-09-2020/newsletter.html?

Can someone please give me a hint what i need to change?

**Comment by einpraegsam** [comment]
To get the number of real issues low, please ask for help in Slack (Channel ext-lux) or on Stackoverflow
