### ISSUE TITLE
Newsletter on domain with umlaut seems not working

### ISSUE THREAD

**Issue by Padina42** [in2code-de/luxletter#58]
A really nice script. 

I tried to post my newletter, which i publish first under https://www.düddelei.de/newsletter-1
Your script can't find it. ....

With best regards 
    Dieter

**Comment by einpraegsam** [comment]
I don't believe that this is related to the extension because only TYPO3 internal functions are used to build links to domains.

**Comment by Padina42** [comment]
I add screenshots, to describe the problem. 
(P.S. aFter moving the page to an domain without umlaut in the same TYPO3-configuration, luxletter works inclusive the preview fine)
If it is a problem of TYPO3, please describe the problem on forge.
Perhaps it is a misconfiguration of the server by my hoster (mittwald). But I tried https://ärger.de/de-de. It shows the same error in the preview.

![2020-10-03 15_27_36-Filme   TV](https://user-images.githubusercontent.com/8037773/94992910-95ff5b80-058d-11eb-89af-8919d921c35f.png)
![2020-10-03 15_27_13-düddelei  TYPO3 CMS 9 5 21](https://user-images.githubusercontent.com/8037773/94992911-97308880-058d-11eb-8bc7-03edb3bec761.png)
![2020-10-03 15_26_28-SVG als Archiv](https://user-images.githubusercontent.com/8037773/94992912-97308880-058d-11eb-8252-6c6392ee36b9.png)


.
