### ISSUE TITLE
Tt_address support

### ISSUE THREAD

**Issue by w010** [in2code-de/luxletter#59]
When do you plan to add tt_address support? How does it come it lacks such a basic feature? Tt_address is for newsletters, fe_users is for user login, since always. Why the table name can't just be configurable? What gonna happen, if I just do mass replace fe_user -> tt_address? Or fe_user -> $this->settings['tableName']? I can't understand the whole situation. Why?

**Comment by einpraegsam** [comment]
Wow, this sounds a bit rude - don't you think? I would suggest you to use a different tool then luxletter.

**Comment by w010** [comment]
I already did use other system. Yes, it was supposed to be kinda rude in that little bit.  I'm just looking here from time to time to check if something changed, if that's the new way of making great newsletters in Typo3, but it's still the same ridiculous situation and I just can't find other words for commenting that. Great extension screwed by bad approach and no will to fix, which is probably simple.
I planned to do this for you, but you chose your pride for little rudeness rather than start a discussion. Good luck then, i'm not wasting your time anymore.
