### ISSUE TITLE
DateTime error when sending newsletter

### ISSUE THREAD

**Issue by ms217** [in2code-de/luxletter#6]
Hello,

we are getting a DateTime error when we try to send a newsletter.

`Return value of In2code\Luxletter\Domain\Model\User::getCrdate() must be an instance of DateTime, null returned`

Environment: PHP 7.3.9, TYPO3 9.5.9, we are using the taskplaner to send the newsletters, not the CLI.

Is this a bug, or might this be caused by a missing/wrong configuration in PHP or T3?

**Comment by einpraegsam** [comment]
Hi, this is related to empty fields in fe_users.crdate - I just pushed a fix to develop branch for this situation. Nevertheless check your database for missing crdate entries.

**Comment by einpraegsam** [comment]
Update: Should be fixed in version 1.1.1

**Comment by ms217** [comment]
Thank you, but your fix didn't fixed the problem because a follow-up exception occured.

However, your hint with the crdate field did the trick. I've no idea how my co-worker imported the users but as already mentioned, saving the records with a valid unix timestamp did the trick.
