### ISSUE TITLE
Wrong number of newsletter subscribers in newsletter list

### ISSUE THREAD

**Issue by cdaecke** [in2code-de/luxletter#60]
As shown in the attached screenshot, the number of the newsletter subscribers in the list of all newsletters is showing the current number of subscribers and not the real number of the newsletter receivers for one newsletter.

<img width="888" alt="Bildschirmfoto 2020-10-12 um 19 58 40" src="https://user-images.githubusercontent.com/2102444/95777255-1af12000-0cc6-11eb-92b3-fa7b00d7a793.png">

I will provide a pull request, which addresses this issue. It will show the numbers from the queue of a newsletter, so the real numbers a newsletter was sent to.

<img width="888" alt="Bildschirmfoto 2020-10-12 um 19 48 47" src="https://user-images.githubusercontent.com/2102444/95777476-863af200-0cc6-11eb-9474-da3a2140db33.png">

**Thank you a big time for this great extension!**

**Comment by einpraegsam** [comment]
You are right, we should change this behaviour. Thx for digging into it.

**Comment by einpraegsam** [comment]
Just merged into develop - ready for upcoming release
