### ISSUE TITLE
Click evaluation for single newsletter

### ISSUE THREAD

**Issue by rintisch** [in2code-de/luxletter#64]
My customer would like to evaluate the opening rate for individual links per newsletter. They are used to it from [EXT:newsletter](https://extensions.typo3.org/extension/newsletter/)

That's how it looked like:
![grafik](https://user-images.githubusercontent.com/44193208/96675847-31eddd00-136c-11eb-9362-75d86f8ccf34.png)

If there is another way to get these data (e.g. somehow with a analytic tool like Google Analytics, e.g. with [utm parameter](https://support.google.com/analytics/answer/1033867?hl=en)) I would be interested as well

**Comment by einpraegsam** [comment]
No, the information is collected but at the moment there is now view for this.
