### ISSUE TITLE
Question: Best practice for „reusable content“ in footer

### ISSUE THREAD

**Issue by lochmueller** [in2code-de/luxletter#65]
Hey Alex,

I have a luxletter installation and have some trouble to create reusable content of another page:
- Newsletter 1 (Should render the content of the Footer Page in the footer)
- Newsletter 2 (Should render the content of the Footer Page  in the footer)
- Footer (Content Elements for every Newsletter)

I try it with a separate ViewHelpers, but got problems with the TSFE. Also try with TS, but also some problems.
Could you send me a hint, how you solve this in the „luxletter“-way?
The rendering via different type nums (Preview, Content generation) and standalone rendering (without page context) is quite complex and complete different than e.g. direct mail.

Regards & thank you,
Tim

**Comment by einpraegsam** [comment]
For the TSFE-problems: See https://github.com/in2code-de/luxletter/issues/45
