### ISSUE TITLE
Improve test mail behaviour

### ISSUE THREAD

**Issue by georgringer** [in2code-de/luxletter#68]
I propose the following changes to sending test emails:

- If the test emails fail, e.g. because content can't be retrieved, an error should be shown instead of just doing nothing. the ajax response shows the exception ` (1/1) #1560709791 In2code\Luxletter\Exception\MisconfigurationException `
- If the test email succeeds, the box to send an email should not be removed as sending another test email should still be possible

another hint: if using self signed certificates, one need to set
```
    'HTTP' => [
      'verify' => false,
    ],
```
maybe that could also be added to the exception or the UI as further explanation

**Comment by georgringer** [comment]
ah just saw, related to https://github.com/in2code-de/luxletter/issues/42

**Comment by einpraegsam** [comment]
Duplicated
