### ISSUE TITLE
Newsletter is always sent with the header of in2code

### ISSUE THREAD

**Issue by danaron** [in2code-de/luxletter#70]
Hi
We did implement the luxletter, in the preview the template from the NewsletterContainer.html file we changed works fine, but when sending the newsletter, there is the in2code template used. How can we change this?
Best regards
Dan

**Comment by danaron** [comment]
Anyone has a suggestion? I want to keep the extension updatable but non of the Templates I checked can change this behavior. Don't tell me one can not customize the template. If so, the extension is useless until you are in2code.
Thank you for your help.
Best regards
Dan
PS: Thinking about using the service with lux enterprise, but as long as it is not working in the open source version, I do not have any trust...

**Comment by einpraegsam** [comment]
Hi Dan,

as long as this project is completely for free, we are working on our spare time on this. So you have to be a little patient.

Alex

P.S.: If you don't want the enterprise solution, don't buy it.

**Comment by danaron** [comment]
Hi Alex,
thank you for your reply. I thought, that the luxletter is part of the enterprise solution and not a project you work on in your spare time, sorry. I did not dig deep into the enterprise solution yet, just had a talk with your sales representativ.

Would be more than happy to sponsor the luxletter the way it works with the Newsletter defined in the file NewsletterContainer.html. Name me the price and we are in.

Really like what I have heard from your sales so fare and it would help the whole TYPO3 community to have a reliably and professional newsletter tool available.

Best regards
Dan

**Comment by einpraegsam** [comment]
Ok, I took the time and tested without problems here on my machine but I can image what issue could be the problem in your case. 

I created a sitepackage extension and required luxletter in the ext_emconf.php.

After that I added a TypoScript template file like:
```
plugin {
	tx_luxletter_fe {
		view {
			templateRootPaths {
				0 = EXT:luxletter/Resources/Private/Templates/
				1 = EXT:sitepackage/Resources/Private/Templates/
			}
			partialRootPaths {
				0 = EXT:luxletter/Resources/Private/Partials/
				1 = EXT:sitepackage/Resources/Private/Partials/
			}
			layoutRootPaths {
				0 = EXT:luxletter/Resources/Private/Layouts/
				1 = EXT:sitepackage/Resources/Private/Layouts/
			}
		}
	}
}
module.tx_luxletter < plugin.tx_luxletter_fe
```

Next I copied the template file NewsletterContainer.html to my sitepackage in EXT:sitepackage/Resources/Private/Templates/Mail/ and modified it a bit with a different header (like logo, etc...)

Now I included the file with a ext_typoscript_setup.typoscript file (that is important to include the TypoScript after the TypoScript of luxletter):
```
@import 'EXT:sitepackage/Configuration/TypoScript/setup.typoscript'
```

When I now check the preview, everything works as expected. I can also create the newsletter and send it and everythink works like a charm.

Can you please try it the same way and give me feedback?

**Comment by danaron** [comment]
Hi Alex,
Thank you for this idea. We tested it and it works. Just don't know, why we need this additional step with a sitepackage extension. Will keep checking it out.
Best regards
Dan

**Comment by einpraegsam** [comment]
This is not related to a sitepackage, even if using a sitepackage is the cleaner way. This is related to the sorting of included TypoScripts (can be checked in TypoScript Object Browser). Nevertheless I will update the documentation with this example.

**Comment by einpraegsam** [comment]
So, I will close this issue if it is solved
