### ISSUE TITLE
Wrong inclusion of Zurb styles

### ISSUE THREAD

**Issue by akiessling** [in2code-de/luxletter#72]
https://github.com/in2code-de/luxletter/blob/5e080d50a69a90a83c039ac9492095d77d866f21/Configuration/TypoScript/FluidStyledMailContent/setup.typoscript#L40

https://github.com/in2code-de/luxletter/blob/5e080d50a69a90a83c039ac9492095d77d866f21/Resources/Private/Partials/Mail/ZurbCss.html#L5-L9

The referenced template contains a <style> Tag, but this only works, if it is included via headerData.
cssInline directly contains styles, see https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Setup/Page/#cssinline-array, thus i ended up with a nested style tag

**Comment by einpraegsam** [comment]
How to produce: Show a page that should be rendered in luxletter via ?type=1562349004 and check the included css. It must not have a style tag in the file.

I just pushed a fix to develop branch.

**Comment by akiessling** [comment]
Looks good, thanks for taking care so quickly! 👍
