### ISSUE TITLE
Priority of template paths for FluidStyledMailContent does not work

### ISSUE THREAD

**Issue by akiessling** [in2code-de/luxletter#73]
https://github.com/in2code-de/luxletter/blob/5e080d50a69a90a83c039ac9492095d77d866f21/Configuration/TypoScript/Basic/Luxletter/03_ContentElements.typoscript#L1-L5

The key 32 has a higher priority than the one in the condition for the email pagetype 

https://github.com/in2code-de/luxletter/blob/5e080d50a69a90a83c039ac9492095d77d866f21/Configuration/TypoScript/FluidStyledMailContent/setup.typoscript#L3-L15

Thus the email templates for e.g. the text content element are never taken from the FluidStyledMailContent setup, if it is installed like suggested in the documentation https://github.com/in2code-de/luxletter/blob/develop/Documentation/Installation/Index.md

Since FLUIDTEMPLATE also does not allow to override / rearrange the order by simply "upgrading" the key, i had to copy the whole config over to an own file and use e.g. 50 instead of 10 for the rootPaths.

**Comment by einpraegsam** [comment]
Ok, digging into your issue leads me to the problem.

**How to reproduce:**
Adding a CE of CType TEXT and render the page with type=1562349004. Now you can see that it's not rendered the ugly way (for newsletters).

I tend to increase all lib.contentElement.xxRootPaths from 10 to 100. What would your suggestion?

**Comment by akiessling** [comment]
Sorry for the missing "how to reproduce", it got a bit late after debugging for a while.
Your solution is exactly how i'd solve it, but if anyone configured own paths at e.g. 50, that will override these styles again. So kind of breaking, but i don't have any other suggestion :/

**Comment by einpraegsam** [comment]
Yes, I also think that this is a breaking change. I will communicate it in the upcoming release.

**Comment by einpraegsam** [comment]
Thx for your help
