### ISSUE TITLE
[Bug] Deleted user recives mail if already in queue

### ISSUE THREAD

**Issue by rr-it** [in2code-de/luxletter#74]
A deleted user who was already queued before deletion will receive a mail. The mail is adressed to her mail-address but without her name (empty string).

This behaviour is introduced with https://github.com/in2code-de/luxletter/issues/71

PR follows.

**Comment by rr-it** [comment]
The actual queue handling of mails for deleted users is not changed.

As a result the mail is not send by `sendNewsletterToReceiverInQueue(Queue $queue)` but still marked as sent. See:

https://github.com/in2code-de/luxletter/blob/67f25f8b7226051e1f3e509a28a02818e283a5aa/Classes/Mail/ProgressQueue.php#L87-L89

**Comment by einpraegsam** [comment]
I just merged the fix to develop. Ready for the upcoming release.
