### ISSUE TITLE
Exception in Luxletter Middleware

### ISSUE THREAD

**Issue by lochmueller** [in2code-de/luxletter#76]
The `$this->luxIdentification($link);` call should be in the `if ($link !== null) {` condition to avoid a exception if the link do not exists (because luxIdentification use a type hint): https://github.com/in2code-de/luxletter/blob/develop/Classes/Middleware/LuxletterLink.php#L49

I will create a pull request if there is enough time next week....

Regards,
Tim

**Comment by einpraegsam** [comment]
Thx, I pushed a fix to develop branch. Ready for the upcoming release.
