### ISSUE TITLE
Luxletter only sends 18 emails instead of all

### ISSUE THREAD

**Issue by danaron** [in2code-de/luxletter#78]
Hi,
I do have the problem that I have a fe user group of 971 users. Then I do generate the newsletter and select the group the displayed number or the group is right (see pic below).

 ![971-users](https://user-images.githubusercontent.com/9381733/105695481-6ee4e500-5f02-11eb-93b4-1322a5715561.jpg)

Then after saving, under Newsletter/Newsletter/ Manage Newsletter only 18 receivers in total are displayed (secound pic below).

![18-users](https://user-images.githubusercontent.com/9381733/105696502-b881ff80-5f03-11eb-8fba-1c8eff16d0d3.jpg)

When I check who received the newsletter under Newsletter Receivers (Newsletter/Empfänger) I can see who got the newsletter and that are only 18 receivers at the end of the alphabeth.

![18-users-stats](https://user-images.githubusercontent.com/9381733/105696265-5de8a380-5f03-11eb-9601-f6f6d0ff53a1.jpg)

Is there a limitation on sending mails? Can you help me to find a solution for this problem? In the cron argument: amount. <em>How many mails should be send per wave?</em> the value is 50.

I can not find a place where the sent emails are logged in the system. Where should that be?
Thanks you for the great extension. Your help is is greatly appreciated.
Best regards
Danaron

**Comment by einpraegsam** [comment]
Ok, can you please provide two screenshots from a user that is included and another user that is not included into receiver list. I'm only interested in the related groups (fe_group) configuration.

**Comment by danaron** [comment]
Hi Alex,
Here are the two screenshots, hope that is what you like to see:
User not send:
![user-not-send](https://user-images.githubusercontent.com/9381733/105725935-d06c7a00-5f29-11eb-87e5-9d48cf2a7130.png)
User send:
![user-sent](https://user-images.githubusercontent.com/9381733/105725939-d1051080-5f29-11eb-8be4-18efad0e9599.png)
The group is assigned for both.
Hope you can see something i don't.
Thanks for your help and please let me know if I can provide you with more infos to solve the mistery!
Best regards
Dan

**Comment by einpraegsam** [comment]
That is really strange - and your receiver group is "Agentur" directly in luxletter?

**Comment by danaron** [comment]
Yes, I did check this in the phpmyadmin in the mysql table and all have this entry. ID=14. Is there may be a limitation or a requirement what else the user has to have?
Thanks for our help.

**Comment by einpraegsam** [comment]
No, I don't havy any clue about limitations here. I would have to debug it - sorry.

**Comment by danaron** [comment]
I checked the DB again and I found out, that the ones not send habe a blank space in front of the email adress. I think this is what causes the problem. Stupid me!

**Comment by einpraegsam** [comment]
ah, ok - so let's say it in a different way: 
The one number shows all fe_user records that are related while the sending only works with valid email addresses
Thx for clarification :)
