### ISSUE TITLE
Mailserver - too many connections

### ISSUE THREAD

**Issue by cdaecke** [in2code-de/luxletter#79]
I am trying to send 100 mails per minute with `ext:luxletter` and get the following error:

> Die Ausführung von Task "Konsolenbefehle ausführen (scheduler)" ist fehlgeschlagen mit folgender Meldung: Expected response code "220" but got code "421", with message "421 4.7.0 mailserver.com Error: too many connections from xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx“.

Is the extension opening a connection to the mailserver for each single email or just one connection for sending all emails in a bunch?

Do you have any hint, how to overcome this error?

Thanks a lot.

**Comment by einpraegsam** [comment]
It's possible that your Mailserver can't send 100 mails at once. I would recommend to reduce the amount to 50 (the default settings). But you have to ask your mail provider how many mails can be send. I think luxletter will open 50 requests (but I'm not totally sure because it is similar to the core functionality) to the server if you configure 50.

**Comment by cdaecke** [comment]
Thanks for your quick reply!

According to my mail provider, I can send 20.000 mails within one hour, so this would be more than 300 per minute. But this is only possible, with one connection for sending the mails.

For the moment I reduced to 90 mails per minute, which is working fine. But as my client sends more than 16.000 emails for one newsletter, it would be nice, to send more than 90 mails per minute to be more quick :-)

**Comment by einpraegsam** [comment]
ok, you could be right that this is not yet possible. For the moment I will close this ticket.

**Comment by cdaecke** [comment]
Do you have plans on changing this?

**Comment by einpraegsam** [comment]
Not in the next time. I have too much tasks on my table sorry.
