### ISSUE TITLE
Exception if unsubscribe page in ext configuration is empty or page not exists

### ISSUE THREAD

**Issue by kanow** [in2code-de/luxletter#8]
If the defined page (in extensions configuration) to unsubscribe from the newsletter is wrong or empty then I become an exception on creating a new newsletter in step 3 (review).

```
(1/1) #1521716622 TYPO3\CMS\Core\Exception\SiteNotFoundException
No site found in root line of page 6
```

I thought that something was wrong with my newsletter page id that was defined in the step before, but it wasn't. The setting for the page to unsubscribe the newsletter was wrong. That was a page they not exists in my project :-).

Maybe a better description in the exception will help to fix this in the configuration.

**Comment by einpraegsam** [comment]
Yes, I think an exception is correct - especially in the current times with GDPR and so on...
Nevertheless there should be a better message.
I will search for a solution.

**Comment by einpraegsam** [comment]
Fixed and will be released with the next version
