### ISSUE TITLE
Number of receiver in backend module for newsletter always takes first state

### ISSUE THREAD

**Issue by rintisch** [in2code-de/luxletter#82]
The backend module _Newsletter_ where the sent newsletter are shown has a column which displays how many receiver this newsletter had. 
This number does not show the correct number but always the number which was correct when this receiver group was chosen the first time.

Here a snapshot: The number of receiver changes but the backend module always shows `1374`:
![grafik](https://user-images.githubusercontent.com/44193208/115509182-6d675680-a27e-11eb-85d1-5875c6c8e345.png)

**Comment by einpraegsam** [comment]
As far as I remember the initial number could be correct. Once you add a newsletter with e.g. 3 receivers, the newsletter is queued for 3. Even if the newsletter is not sent yet - if you now add a 4th fe_user the queue is still 3. You would have to re-queue it.

**Comment by rintisch** [comment]
I guess I did not describe correctly the situation:

1. A newsletter is created with the receiver group `Newsletter` for the page `domain.com/newsletter`. At this moment there are `1374` receiver in the user group.
1. One week later a new newsletter is created for the same page  `domain.com/newsletter`. In between more users have the user group `Newsletter`. But nevertheless the backendmodule still displays `1374`.

**Comment by rintisch** [comment]
@einpraegsam 
This problem is solved with v3.1.2 (I had version 2.x.x installed).

Close this issue.
