### ISSUE TITLE
Queue stucked because of removing newsletter usergroup while sending

### ISSUE THREAD

**Issue by rintisch** [in2code-de/luxletter#83]
The queue was stucked because a backend user removed the newsletter usergroup from a frontend user while the queue was processed.

![grafik](https://user-images.githubusercontent.com/44193208/117259213-1cdf2400-ae4e-11eb-8a8c-347a854be333.png)

It was version 2.x - don't know whether something changed in between...

**Comment by einpraegsam** [comment]
The return value of Queue->getUser() can be null since some time. Please use an update version.

Greetings, Alex

**Comment by rintisch** [comment]
Thanks for the feedback (and fixing it in advance ;) ). 
I use already an updated version.
