### ISSUE TITLE
Multiple widgets not working without ext:lux

### ISSUE THREAD

**Issue by dahaupt** [in2code-de/luxletter#84]
Multiple widgets (e.g. widget **luxletterOpenRate**) are using the class `In2code\Lux\Utility\ObjectUtility`, which results in an error in case ext:lux is not installed.

**Comment by einpraegsam** [comment]
Thx for the feedback. Will check and fix this asap.

**Comment by einpraegsam** [comment]
Thx, I pushed a fix to develop branch - ready for the upcoming release

**Comment by dahaupt** [comment]
@einpraegsam Thanks a lot for your fast fix, have a great day! :rocket:

**Comment by einpraegsam** [comment]
No, thank you for the helpful feedback
