### ISSUE TITLE
Problems with site configuration

### ISSUE THREAD

**Issue by alexingo** [in2code-de/luxletter#85]
Hi! I've updated to Typo3 10.4.16 and Luxletter 4.0.0. With **www**.domain.org I get this error in preview: 
Error: Origin https://www.xxx.de/newsletter-june-2021/ could not be converted into a valid url!
Reason: Base settings in site configuration is not in format "https://domain.org/" (1622832844)

When I change url in site configuration without www - the site itself doesn't work!?

**Comment by einpraegsam** [comment]
Hi,

can you please post your site configuration here?
In addition: Did you see the breaking changes in documentation: https://github.com/in2code-de/luxletter#breaking-changes-

Alex

**Comment by alexingo** [comment]
Thanks for your reply! Yes, I saw the breaking changes and added senderConfiguration ...
My site configuration is like that:
base: 'https://www.testdomain.de'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=88'
languages:
  -
    title: Deutsch
    enabled: true
    base: 'https://www.testdomain.de'
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
    languageId: 0
    websiteTitle: 'TestDomain'
luxletterUnsubscribePid: '156'
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    index: ''
    suffix: /
    map:
      preview.html: 1560777975
      newsletter.html: 1562349004
websiteTitle: 'TestDomain'

**Comment by einpraegsam** [comment]
Just add a slash at the end of your base configuration - so `base: 'https://www.testdomain.de/'` and try again pls

**Comment by alexingo** [comment]
Ok, thanks a lot - it works! We didn't have any problems with the missing slash until now in other T9 or T10 installations - but we will change this!
Best regards :)

**Comment by einpraegsam** [comment]
Thx for your final note here
