### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by danaron** [in2code-de/luxletter#87]
Hi
I update a running luxletter extension and after that when I like to create a luxletter there is that error:
Noch keine Konfiguration vorhanden
Bitte erstelle zuerst eine Senderkonfiguration in einem Sysfolder
What do I need to configure?
Thanks for your help.
Best regards
Danaron

**Comment by einpraegsam** [comment]
Did you see and follow the update instructions in the documentation:
https://github.com/in2code-de/luxletter#upgrade-to-4x

**Comment by einpraegsam** [comment]
Any feedback for me?

**Comment by danaron** [comment]
I am abroad at the moment. Will check it next week. Thanks!

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by einpraegsam** [comment]
No problem, I will close this issue for now. Feel free to reopen if there is still a problem.
