### ISSUE TITLE
Fetch correct built base domain from site configuration

### ISSUE THREAD

**Issue by spoonerWeb** [in2code-de/luxletter#88]
## Current behaviour

Currently the extension looks into the field `base` of the site configuration, but in some cases with multiple stage systems the base is only set to `/` and the domain is set in the base variants. This leads to an error when trying to send the queued mails.

## FIx

The `Site` object can build the current used based defined in the site configuration.
Instead of using `$site->getConfiguration()['base']` it should use `(string)$site->getBase()` to get the base domain.
Additionally there should be a check if the base ends with a `/`.

**Comment by einpraegsam** [comment]
Hi again Spoony,

thx for digging into it.
Let's start: I'm aware of the possible problem if only a slash is set. This is also described in the manual and in the new field in the site configuration itself.
I was also aware of base variants. But in default installation you can change the domain in the base variants by a ENV variable or via context (what's nearly the same). The problem in my eyes is (not tested - only theoretical so far), that newsletters are rendered in CLI-context. And normally there are no ENV-variables available on CLI (as long as you do not prefix them in the calls).
So are you really sure, that your change has an impact?

Greetings from Rosenheim to Stuttgart, Alex

**Comment by einpraegsam** [comment]
Any feedback for me?

**Comment by einpraegsam** [comment]
I think it's not needed any more because of https://github.com/in2code-de/luxletter/pull/97
