### ISSUE TITLE
Additional signal in ParseNewsletterService

### ISSUE THREAD

**Issue by georgringer** [in2code-de/luxletter#95]
Checking the code
```php
$standaloneView->assignMultiple($properties);
$string = $standaloneView->render();
$this->signalDispatch(__CLASS__, __FUNCTION__, [&$string, $properties, $this]);
```
it would be cool to have an additional signal *before* the render function to assign additional variables (or modify other properties of the StandaloneView).

**Comment by einpraegsam** [comment]
Pushed a commit to develop with this change
