### ISSUE TITLE
Forward text type to parseMailText

### ISSUE THREAD

**Issue by georgringer** [in2code-de/luxletter#96]
The method `ParseNewsletterService::parseMailText` is used for the subject and the bodytext.

I am using the signal to enrich the bodytext but there is no non-hacky way to define if the method is triggered for the subject or the bodytext. 

As the method is called `parseMailText` and the 1st argument `bodytext` I propose to add another method `parseMailSubject`, and move all the standalone creating code to a protected method which can be used by both methods

**Comment by einpraegsam** [comment]
Feature just pushed to develop

**Comment by georgringer** [comment]
awesome. just a hint @einpraegsam : the method `parseMailText` should get a different name I guess

**Comment by georgringer** [comment]
because it doesn't fit the usage but really just a nitpick ;)

**Comment by einpraegsam** [comment]
I also thought about the wording and I tolerated "mailText" as any kind of text related to a mail - could be bodytext but could also be another text field
